# Proyecto Final Johnatan Meo√±o Titanic

In [1]:
import pandas as pd
import numpy as np
import seaborn as sb 
import matplotlib.pyplot as plt

In [2]:
import tensorflow as tf

C:\Users\Johnatan\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

### Cargag de datos

In [3]:
data = pd.read_csv('data_titanic_proyecto.csv')

In [4]:
## set de datos completo 
data

,PassengerId,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,passenger_class,passenger_sex,passenger_survived
0,1,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S,Lower,M,N
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C,Upper,F,Y
2,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Lower,F,Y
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,Upper,F,Y
4,5,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S,Lower,M,N
5,6,"Moran, Mr. James",NaN,0,0,330877,8.4583,NaN,Q,Lower,M,N
6,7,"McCarthy, Mr. Timothy J",54.0,0,0,17463,51.8625,E46,S,Upper,M,N
7,8,"Palsson, Master. Gosta Leonard",2.0,3,1,349909,21.0750,NaN,S,Lower,M,N
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",27.0,0,2,347742,11.1333,NaN,S,Lower,F,Y
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",14.0,1,0,237736,30.0708,NaN,C,Middle,F,Y
10,11,"Sandstrom, Miss. Marguerite Rut",4.0,1,1,PP 9549,16.7000,G6,S,Lower,F,Y
11,12,"Bonnell, Miss. Elizabeth",58.0,0,0,113783,26.5500,C103,S,Upper,F,Y
12,13,"Saundercock, Mr. William Henry",20.0,0,0,A/5. 2151,8.0500,NaN,S,Lower,M,N
13,14,"Andersson, Mr. Anders Johan",39.0,1,5,347082,31.2750,NaN,S,Lower,M,N
14,15,"Vestrom, Miss. Hulda Amanda Adolfina",14.0,0,0,350406,7.8542,NaN,S,Lower,F,N
15,16,"Hewlett, Mrs. (Mary D Kingcome)",55.0,0,0,248706,16.0000,NaN,S,Middle,F,Y
16,17,"Rice, Master. Eugene",2.0,4,1,382652,29.1250,NaN,Q,Lower,M,N
17,18,"Williams, Mr. Charles Eugene",NaN,0,0,244373,13.0000,NaN,S,Middle,M,Y
18,19,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",31.0,1,0,345763,18.0000,NaN,S,Lower,F,N
19,20,"Masselmani, Mrs. Fatima",NaN,0,0,2649,7.2250,NaN,C,Lower,F,Y
20,21,"Fynney, Mr. Joseph J",35.0,0,0,239865,26.0000,NaN,S,Middle,M,N
21,22,"Beesley, Mr. Lawrence",34.0,0,0,248698,13.0000,D56,S,Middle,M,Y
22,23,"McGowan, Miss. Anna ""Annie""",15.0,0,0,330923,8.0292,NaN,Q,Lower,F,Y
23,24,"Sloper, Mr. William Thompson",28.0,0,0,113788,35.5000,A6,S,Upper,M,Y
24,25,"Palsson, Miss. Torborg Danira",8.0,3,1,349909,21.0750,NaN,S,Lower,F,N
25,26,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",38.0,1,5,347077,31.3875,NaN,S,Lower,F,Y
26,27,"Emir, Mr. Farred Chehab",NaN,0,0,2631,7.2250,NaN,C,Lower,M,N
27,28,"Fortune, Mr. Charles Alexander",19.0,3,2,19950,263.0000,C23 C25 C27,S,Upper,M,N
28,29,"O'Dwyer, Miss. Ellen ""Nellie""",NaN,0,0,330959,7.8792,NaN,Q,Lower,F,Y
29,30,"Todoroff, Mr. Lalio",NaN,0,0,349216,7.8958,NaN,S,Lower,M,N
...,...,...,...,...,...,...,...,...,...,...,...,...
861,862,"Giles, Mr. Frederick Edward",21.0,1,0,28134,11.5000,NaN,S,Middle,M,N
862,863,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",48.0,0,0,17466,25.9292,D17,S,Upper,F,Y
863,864,"Sage, Miss. Dorothy Edith ""Dolly""",NaN,8,2,CA. 2343,69.5500,NaN,S,Lower,F,N
864,865,"Gill, Mr. John William",24.0,0,0,233866,13.0000,NaN,S,Middle,M,N
865,866,"Bystrom, Mrs. (Karolina)",42.0,0,0,236852,13.0000,NaN,S,Middle,F,Y
866,867,"Duran y More, Miss. Asuncion",27.0,1,0,SC/PARIS 2149,13.8583,NaN,C,Middle,F,Y
867,868,"Roebling, Mr. Washington Augustus II",31.0,0,0,PC 17590,50.4958,A24,S,Upper,M,N
868,869,"van Melkebeke, Mr. Philemon",NaN,0,0,345777,9.5000,NaN,S,Lower,M,N
869,870,"Johnson, Master. Harold Theodor",4.0,1,1,347742,11.1333,NaN,S,Lower,M,Y
870,871,"Balkic, Mr. Cerin",26.0,0,0,349248,7.8958,NaN,S,Lower,M,N
871,872,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",47.0,1,1,11751,52.5542,D35,S,Upper,F,Y
872,873,"Carlsson, Mr. Frans Olof",33.0,0,0,695,5.0000,B51 B53 B55,S,Upper,M,N
873,874,"Vander Cruyssen, Mr. Victor",47.0,0,0,345765,9.0000,NaN,S,Lower,M,N
874,875,"Abelson, Mrs. Samuel (Hannah Wizosky)",28.0,1,0,P/PP 3381,24.0000,NaN,C,Middle,F,Y
875,876,"Najib, Miss. Adele Kiamie ""Jane""",15.0,0,0,2667,7.2250,NaN,C,Lower,F,Y
876,877,"Gustafsson, Mr. Alfred Ossian",20.0,0,0,7534,9.8458,NaN,S,Lower,M,N
877,878,"Petroff, Mr. Nedelio",19.0,0,0,349212,7.8958,NaN,S,Lower,M,N
878,879,"Laleff, Mr. Kristo",NaN,0,0,349217,7.8958,NaN,S,Lower,M,N
879,880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",56.0,0,1,11767,83.1583,C50,C,Upper,F,Y
880,881,"Shelley, Mrs. William (Imanita Parrish Hall)",25.0,0,1,230433,26.0000,NaN,S,Middle,F,Y
881,882,"Markun, Mr. Johann",33.0,0,0,349257,7.8958,NaN,S,Lower,M,N
882,883,"Dahlberg, Miss. Gerda Ulrika",22.0,0,0,7552,10.5167,NaN,S,Lower,F,N
883,884,"Banfield, Mr. Frederick James",28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S,Middle,M,N
884,885,"Sutehall, Mr. Henry Jr",25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S,Lower,M,N
885,886,"Rice, Mrs. William (Margaret Norton)",39.0,0,5,382652,29.1250,NaN,Q,Lower,F,N
886,887,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,NaN,S,Middle,M,N
887,888,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,B42,S,Upper,F,Y
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,1,2,W./C. 6607,23.4500,NaN,S,Lower,F,N
889,890,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,C148,C,Upper,M,Y
890,891,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,NaN,Q,Lower,M,N

In [5]:
data.isnull().sum()

PassengerId             0
Name                    0
Age                   177
SibSp                   0
Parch                   0
Ticket                  0
Fare                    0
Cabin                 687
Embarked                2
passenger_class         0
passenger_sex           0
passenger_survived      0
dtype: int64

In [6]:
data.passenger_class.unique()

array(['Lower', 'Upper', 'Middle'], dtype=object)

In [7]:
data.passenger_sex.unique()

array(['M', 'F'], dtype=object)

In [8]:
data.passenger_survived.unique()

array(['N', 'Y'], dtype=object)

## Selecci√≥n de variables

In [9]:
## elimininando las columnas del data set que no voy a utilizar
data1 = data.drop(['PassengerId','Name','Ticket','Fare','Cabin','Embarked'], axis=1)

In [10]:
## set de datos reducido 
data1

      Age  SibSp  Parch passenger_class passenger_sex passenger_survived
0    22.0      1      0           Lower             M                  N
1    38.0      1      0           Upper             F                  Y
2    26.0      0      0           Lower             F                  Y
3    35.0      1      0           Upper             F                  Y
4    35.0      0      0           Lower             M                  N
5     NaN      0      0           Lower             M                  N
6    54.0      0      0           Upper             M                  N
7     2.0      3      1           Lower             M                  N
8    27.0      0      2           Lower             F                  Y
9    14.0      1      0          Middle             F                  Y
10    4.0      1      1           Lower             F                  Y
11   58.0      0      0           Upper             F                  Y
12   20.0      0      0           Lower             M                  N
13   39.0      1      5           Lower             M                  N
14   14.0      0      0           Lower             F                  N
15   55.0      0      0          Middle             F                  Y
16    2.0      4      1           Lower             M                  N
17    NaN      0      0          Middle             M                  Y
18   31.0      1      0           Lower             F                  N
19    NaN      0      0           Lower             F                  Y
20   35.0      0      0          Middle             M                  N
21   34.0      0      0          Middle             M                  Y
22   15.0      0      0           Lower             F                  Y
23   28.0      0      0           Upper             M                  Y
24    8.0      3      1           Lower             F                  N
25   38.0      1      5           Lower             F                  Y
26    NaN      0      0           Lower             M                  N
27   19.0      3      2           Upper             M                  N
28    NaN      0      0           Lower             F                  Y
29    NaN      0      0           Lower             M                  N
..    ...    ...    ...             ...           ...                ...
861  21.0      1      0          Middle             M                  N
862  48.0      0      0           Upper             F                  Y
863   NaN      8      2           Lower             F                  N
864  24.0      0      0          Middle             M                  N
865  42.0      0      0          Middle             F                  Y
866  27.0      1      0          Middle             F                  Y
867  31.0      0      0           Upper             M                  N
868   NaN      0      0           Lower             M                  N
869   4.0      1      1           Lower             M                  Y
870  26.0      0      0           Lower             M                  N
871  47.0      1      1           Upper             F                  Y
872  33.0      0      0           Upper             M                  N
873  47.0      0      0           Lower             M                  N
874  28.0      1      0          Middle             F                  Y
875  15.0      0      0           Lower             F                  Y
876  20.0      0      0           Lower             M                  N
877  19.0      0      0           Lower             M                  N
878   NaN      0      0           Lower             M                  N
879  56.0      0      1           Upper             F                  Y
880  25.0      0      1          Middle             F                  Y
881  33.0      0      0           Lower             M                  N
882  22.0      0      0           Lower             F                  N
883  28.0      0      0          Middle             M                  N
884  25.0      0      0           Lower             M                  N
885  39.0      0      5           Lower             F                  N
886  27.0      0      0          Middle             M                  N
887  19.0      0      0           Upper             F                  Y
888   NaN      1      2           Lower             F                  N
889  26.0      0      0           Upper             M                  Y
890  32.0      0      0           Lower             M                  N

[891 rows x 6 columns]

In [11]:
#data[['passenger_class']].values.reshape((891)).ndim
#data[['passenger_sex']].values.reshape((891)).ndim
#data[['passenger_survived']].values.reshape((891)).ndim

In [12]:
## unique de tensor flow necesita recibir estas etiquetas como un vector (rango 1) por eso se hace reshape 891
clase = data1[['passenger_class']].values.reshape((891))
sexo = data1[['passenger_sex']].values.reshape((891))
vive = data1[['passenger_survived']].values.reshape((891))

In [13]:
vive.ndim

1

## Feature engieniering: pasando las etiquetas a valores n√∫mericos

In [14]:
grafoonehot = tf.Graph()
with grafoonehot.as_default():
    ## definiendo el vector de las etiquetas como cosntantes
    etiquetas1 = tf.constant(clase)
    etiquetas2 = tf.constant(sexo)
    etiquetas3 = tf.constant(vive)
    
    ## aplicando valores unicos
    ## la "y" da los valores unicos
    ## idx indexa cada valor unico haciendo que a lo largo de los
    ## datos cada valor unico tenga el mismo indice 
    yunicos1, idx1 = tf.unique(etiquetas1)
    yunicos2, idx2 = tf.unique(etiquetas2)
    yunicos3, idx3 = tf.unique(etiquetas3)
    
    ## haciendo one hot sobre los indicses idx
    #hot = tf.one_hot(idx, depth = 120)
    
    ## calcula el maximo del indice para comprobar que indexo 120 razas
    #maximo = tf.reduce_max(idx)

In [15]:
with tf.Session(graph = grafoonehot ) as sesiononehot:
    _class, _sex, _survived  = sesiononehot.run([idx1, idx2, idx3])
    _label1, _label2, _label3 = sesiononehot.run([yunicos1, yunicos2, yunicos3])

In [16]:
_label1

array([b'Lower', b'Upper', b'Middle'], dtype=object)

In [17]:
## ya que tensor flow devuelve un vector se hace reshape para convertirlo a matriz de
## 891 filas y una columna 
clasen = _class.reshape((891,1))
clasen.ndim

2

In [18]:
sexn = _sex.reshape((891,1))
sexn.ndim

2

In [19]:
viven = _survived.reshape((891,1))
viven.ndim

2

In [20]:
## copia de los datos 
data2 = data1

In [21]:
data2

      Age  SibSp  Parch passenger_class passenger_sex passenger_survived
0    22.0      1      0           Lower             M                  N
1    38.0      1      0           Upper             F                  Y
2    26.0      0      0           Lower             F                  Y
3    35.0      1      0           Upper             F                  Y
4    35.0      0      0           Lower             M                  N
5     NaN      0      0           Lower             M                  N
6    54.0      0      0           Upper             M                  N
7     2.0      3      1           Lower             M                  N
8    27.0      0      2           Lower             F                  Y
9    14.0      1      0          Middle             F                  Y
10    4.0      1      1           Lower             F                  Y
11   58.0      0      0           Upper             F                  Y
12   20.0      0      0           Lower             M                  N
13   39.0      1      5           Lower             M                  N
14   14.0      0      0           Lower             F                  N
15   55.0      0      0          Middle             F                  Y
16    2.0      4      1           Lower             M                  N
17    NaN      0      0          Middle             M                  Y
18   31.0      1      0           Lower             F                  N
19    NaN      0      0           Lower             F                  Y
20   35.0      0      0          Middle             M                  N
21   34.0      0      0          Middle             M                  Y
22   15.0      0      0           Lower             F                  Y
23   28.0      0      0           Upper             M                  Y
24    8.0      3      1           Lower             F                  N
25   38.0      1      5           Lower             F                  Y
26    NaN      0      0           Lower             M                  N
27   19.0      3      2           Upper             M                  N
28    NaN      0      0           Lower             F                  Y
29    NaN      0      0           Lower             M                  N
..    ...    ...    ...             ...           ...                ...
861  21.0      1      0          Middle             M                  N
862  48.0      0      0           Upper             F                  Y
863   NaN      8      2           Lower             F                  N
864  24.0      0      0          Middle             M                  N
865  42.0      0      0          Middle             F                  Y
866  27.0      1      0          Middle             F                  Y
867  31.0      0      0           Upper             M                  N
868   NaN      0      0           Lower             M                  N
869   4.0      1      1           Lower             M                  Y
870  26.0      0      0           Lower             M                  N
871  47.0      1      1           Upper             F                  Y
872  33.0      0      0           Upper             M                  N
873  47.0      0      0           Lower             M                  N
874  28.0      1      0          Middle             F                  Y
875  15.0      0      0           Lower             F                  Y
876  20.0      0      0           Lower             M                  N
877  19.0      0      0           Lower             M                  N
878   NaN      0      0           Lower             M                  N
879  56.0      0      1           Upper             F                  Y
880  25.0      0      1          Middle             F                  Y
881  33.0      0      0           Lower             M                  N
882  22.0      0      0           Lower             F                  N
883  28.0      0      0          Middle             M                  N
884  25.0      0      0           Lower             M                  N
885  39.0      0      5           Lower             F                  N
886  27.0      0      0          Middle             M                  N
887  19.0      0      0           Upper             F                  Y
888   NaN      1      2           Lower             F                  N
889  26.0      0      0           Upper             M                  Y
890  32.0      0      0           Lower             M                  N

[891 rows x 6 columns]

In [22]:
## agregar la edad normalizada 
data2['Agee'] = data2.Age / 100

In [23]:
## se agregan las nuevas columnas al data frame data2
data2['passenger_classs'] = clasen

In [24]:
data2['passenger_sexx'] = sexn

In [25]:
data2['passenger_survivedd'] = viven

In [26]:
data2

,Age,SibSp,Parch,passenger_class,passenger_sex,passenger_survived,Agee,passenger_classs,passenger_sexx,passenger_survivedd
0,22.0,1,0,Lower,M,N,0.22,0,0,0
1,38.0,1,0,Upper,F,Y,0.38,1,1,1
2,26.0,0,0,Lower,F,Y,0.26,0,1,1
3,35.0,1,0,Upper,F,Y,0.35,1,1,1
4,35.0,0,0,Lower,M,N,0.35,0,0,0
5,NaN,0,0,Lower,M,N,NaN,0,0,0
6,54.0,0,0,Upper,M,N,0.54,1,0,0
7,2.0,3,1,Lower,M,N,0.02,0,0,0
8,27.0,0,2,Lower,F,Y,0.27,0,1,1
9,14.0,1,0,Middle,F,Y,0.14,2,1,1
10,4.0,1,1,Lower,F,Y,0.04,0,1,1
11,58.0,0,0,Upper,F,Y,0.58,1,1,1
12,20.0,0,0,Lower,M,N,0.20,0,0,0
13,39.0,1,5,Lower,M,N,0.39,0,0,0
14,14.0,0,0,Lower,F,N,0.14,0,1,0
15,55.0,0,0,Middle,F,Y,0.55,2,1,1
16,2.0,4,1,Lower,M,N,0.02,0,0,0
17,NaN,0,0,Middle,M,Y,NaN,2,0,1
18,31.0,1,0,Lower,F,N,0.31,0,1,0
19,NaN,0,0,Lower,F,Y,NaN,0,1,1
20,35.0,0,0,Middle,M,N,0.35,2,0,0
21,34.0,0,0,Middle,M,Y,0.34,2,0,1
22,15.0,0,0,Lower,F,Y,0.15,0,1,1
23,28.0,0,0,Upper,M,Y,0.28,1,0,1
24,8.0,3,1,Lower,F,N,0.08,0,1,0
25,38.0,1,5,Lower,F,Y,0.38,0,1,1
26,NaN,0,0,Lower,M,N,NaN,0,0,0
27,19.0,3,2,Upper,M,N,0.19,1,0,0
28,NaN,0,0,Lower,F,Y,NaN,0,1,1
29,NaN,0,0,Lower,M,N,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...
861,21.0,1,0,Middle,M,N,0.21,2,0,0
862,48.0,0,0,Upper,F,Y,0.48,1,1,1
863,NaN,8,2,Lower,F,N,NaN,0,1,0
864,24.0,0,0,Middle,M,N,0.24,2,0,0
865,42.0,0,0,Middle,F,Y,0.42,2,1,1
866,27.0,1,0,Middle,F,Y,0.27,2,1,1
867,31.0,0,0,Upper,M,N,0.31,1,0,0
868,NaN,0,0,Lower,M,N,NaN,0,0,0
869,4.0,1,1,Lower,M,Y,0.04,0,0,1
870,26.0,0,0,Lower,M,N,0.26,0,0,0
871,47.0,1,1,Upper,F,Y,0.47,1,1,1
872,33.0,0,0,Upper,M,N,0.33,1,0,0
873,47.0,0,0,Lower,M,N,0.47,0,0,0
874,28.0,1,0,Middle,F,Y,0.28,2,1,1
875,15.0,0,0,Lower,F,Y,0.15,0,1,1
876,20.0,0,0,Lower,M,N,0.20,0,0,0
877,19.0,0,0,Lower,M,N,0.19,0,0,0
878,NaN,0,0,Lower,M,N,NaN,0,0,0
879,56.0,0,1,Upper,F,Y,0.56,1,1,1
880,25.0,0,1,Middle,F,Y,0.25,2,1,1
881,33.0,0,0,Lower,M,N,0.33,0,0,0
882,22.0,0,0,Lower,F,N,0.22,0,1,0
883,28.0,0,0,Middle,M,N,0.28,2,0,0
884,25.0,0,0,Lower,M,N,0.25,0,0,0
885,39.0,0,5,Lower,F,N,0.39,0,1,0
886,27.0,0,0,Middle,M,N,0.27,2,0,0
887,19.0,0,0,Upper,F,Y,0.19,1,1,1
888,NaN,1,2,Lower,F,N,NaN,0,1,0
889,26.0,0,0,Upper,M,Y,0.26,1,0,1
890,32.0,0,0,Lower,M,N,0.32,0,0,0

In [27]:
## se crea un dataset nuevo suprimiendo las columnas cque no se necesitan pues tienen etiquetas
data3 = data2.drop(['Age','passenger_class','passenger_sex','passenger_survived'], axis=1)

In [28]:
data3

     SibSp  Parch  Agee  passenger_classs  passenger_sexx  passenger_survivedd
0        1      0  0.22                 0               0                    0
1        1      0  0.38                 1               1                    1
2        0      0  0.26                 0               1                    1
3        1      0  0.35                 1               1                    1
4        0      0  0.35                 0               0                    0
5        0      0   NaN                 0               0                    0
6        0      0  0.54                 1               0                    0
7        3      1  0.02                 0               0                    0
8        0      2  0.27                 0               1                    1
9        1      0  0.14                 2               1                    1
10       1      1  0.04                 0               1                    1
11       0      0  0.58                 1               1                    1
12       0      0  0.20                 0               0                    0
13       1      5  0.39                 0               0                    0
14       0      0  0.14                 0               1                    0
15       0      0  0.55                 2               1                    1
16       4      1  0.02                 0               0                    0
17       0      0   NaN                 2               0                    1
18       1      0  0.31                 0               1                    0
19       0      0   NaN                 0               1                    1
20       0      0  0.35                 2               0                    0
21       0      0  0.34                 2               0                    1
22       0      0  0.15                 0               1                    1
23       0      0  0.28                 1               0                    1
24       3      1  0.08                 0               1                    0
25       1      5  0.38                 0               1                    1
26       0      0   NaN                 0               0                    0
27       3      2  0.19                 1               0                    0
28       0      0   NaN                 0               1                    1
29       0      0   NaN                 0               0                    0
..     ...    ...   ...               ...             ...                  ...
861      1      0  0.21                 2               0                    0
862      0      0  0.48                 1               1                    1
863      8      2   NaN                 0               1                    0
864      0      0  0.24                 2               0                    0
865      0      0  0.42                 2               1                    1
866      1      0  0.27                 2               1                    1
867      0      0  0.31                 1               0                    0
868      0      0   NaN                 0               0                    0
869      1      1  0.04                 0               0                    1
870      0      0  0.26                 0               0                    0
871      1      1  0.47                 1               1                    1
872      0      0  0.33                 1               0                    0
873      0      0  0.47                 0               0                    0
874      1      0  0.28                 2               1                    1
875      0      0  0.15                 0               1                    1
876      0      0  0.20                 0               0                    0
877      0      0  0.19                 0               0                    0
878      0      0   NaN                 0               0                    0
879      0      1  0.56                 1               1                    1
880      0      1  0.25                 2               1                    1
881      0      0  0.33                 0               0                    0
882      0      0  0.22                 0               1                    0
883      0      0  0.28                 2               0                    0
884      0      0  0.25                 0               0                    0
885      0      5  0.39                 0               1                    0
886      0      0  0.27                 2               0                    0
887      0      0  0.19                 1               1                    1
888      1      2   NaN                 0               1                    0
889      0      0  0.26                 1               0                    1
890      0      0  0.32                 0               0                    0

[891 rows x 6 columns]

In [29]:
## revisando cada columna, para saber si tiene valores NaN
data3.isnull().sum()

SibSp                    0
Parch                    0
Agee                   177
passenger_classs         0
passenger_sexx           0
passenger_survivedd      0
dtype: int64

In [30]:
## quitando los NaN del dataframe y se crea un data frame nuevo
data4 =  data3.dropna()

In [31]:
data4

     SibSp  Parch  Agee  passenger_classs  passenger_sexx  passenger_survivedd
0        1      0  0.22                 0               0                    0
1        1      0  0.38                 1               1                    1
2        0      0  0.26                 0               1                    1
3        1      0  0.35                 1               1                    1
4        0      0  0.35                 0               0                    0
6        0      0  0.54                 1               0                    0
7        3      1  0.02                 0               0                    0
8        0      2  0.27                 0               1                    1
9        1      0  0.14                 2               1                    1
10       1      1  0.04                 0               1                    1
11       0      0  0.58                 1               1                    1
12       0      0  0.20                 0               0                    0
13       1      5  0.39                 0               0                    0
14       0      0  0.14                 0               1                    0
15       0      0  0.55                 2               1                    1
16       4      1  0.02                 0               0                    0
18       1      0  0.31                 0               1                    0
20       0      0  0.35                 2               0                    0
21       0      0  0.34                 2               0                    1
22       0      0  0.15                 0               1                    1
23       0      0  0.28                 1               0                    1
24       3      1  0.08                 0               1                    0
25       1      5  0.38                 0               1                    1
27       3      2  0.19                 1               0                    0
30       0      0  0.40                 1               0                    0
33       0      0  0.66                 2               0                    0
34       1      0  0.28                 1               0                    0
35       1      0  0.42                 1               0                    0
37       0      0  0.21                 0               0                    0
38       2      0  0.18                 0               1                    0
..     ...    ...   ...               ...             ...                  ...
856      1      1  0.45                 1               1                    1
857      0      0  0.51                 1               0                    1
858      0      3  0.24                 0               1                    1
860      2      0  0.41                 0               0                    0
861      1      0  0.21                 2               0                    0
862      0      0  0.48                 1               1                    1
864      0      0  0.24                 2               0                    0
865      0      0  0.42                 2               1                    1
866      1      0  0.27                 2               1                    1
867      0      0  0.31                 1               0                    0
869      1      1  0.04                 0               0                    1
870      0      0  0.26                 0               0                    0
871      1      1  0.47                 1               1                    1
872      0      0  0.33                 1               0                    0
873      0      0  0.47                 0               0                    0
874      1      0  0.28                 2               1                    1
875      0      0  0.15                 0               1                    1
876      0      0  0.20                 0               0                    0
877      0      0  0.19                 0               0                    0
879      0      1  0.56                 1               1                    1
880      0      1  0.25                 2               1                    1
881      0      0  0.33                 0               0                    0
882      0      0  0.22                 0               1                    0
883      0      0  0.28                 2               0                    0
884      0      0  0.25                 0               0                    0
885      0      5  0.39                 0               1                    0
886      0      0  0.27                 2               0                    0
887      0      0  0.19                 1               1                    1
889      0      0  0.26                 1               0                    1
890      0      0  0.32                 0               0                    0

[714 rows x 6 columns]

In [32]:
## revisando que no haya quedado ningun NaN
data4.isnull().sum()

SibSp                  0
Parch                  0
Agee                   0
passenger_classs       0
passenger_sexx         0
passenger_survivedd    0
dtype: int64

In [33]:
#seem = 5

## Separaci√≥n de data4 en: train, validation, test

In [34]:
## esta llamanada sirve para la fucion que separara datos 
from sklearn.model_selection import train_test_split

In [35]:
## convirtiendo data frame de pandas a numpy array
datos = data4.values

In [36]:
print("Rango: ", datos.ndim)
print("Forma: ", datos.shape)
print("Tipy: ", type(datos))
print(datos)

Rango:  2
Forma:  (714, 6)
Tipy:  <class 'numpy.ndarray'>
[[1.   0.   0.22 0.   0.   0.  ]
 [1.   0.   0.38 1.   1.   1.  ]
 [0.   0.   0.26 0.   1.   1.  ]
 ...
 [0.   0.   0.19 1.   1.   1.  ]
 [0.   0.   0.26 1.   0.   1.  ]
 [0.   0.   0.32 0.   0.   0.  ]]

In [37]:
## separacion de datos 
train_vali, test = train_test_split(datos, test_size=0.20) #, random_state=seem

In [38]:
print("Rango: ", train_vali.ndim)
print("Forma: ", train_vali.shape)
print("Tipy: ", type(train_vali))
print(train_vali)

Rango:  2
Forma:  (571, 6)
Tipy:  <class 'numpy.ndarray'>
[[0.   0.   0.3  0.   0.   0.  ]
 [1.   0.   0.63 1.   1.   1.  ]
 [0.   0.   0.42 0.   0.   0.  ]
 ...
 [0.   0.   0.3  2.   0.   0.  ]
 [0.   0.   0.28 1.   0.   1.  ]
 [0.   0.   0.63 0.   1.   1.  ]]

## Test

In [39]:
print("Rango: ", test.ndim)
print("Forma: ", test.shape)
print("Tipy: ", type(test))
print(test)

Rango:  2
Forma:  (143, 6)
Tipy:  <class 'numpy.ndarray'>
[[1.     0.     0.48   1.     1.     1.    ]
 [1.     0.     0.24   0.     1.     1.    ]
 [0.     2.     0.405  0.     0.     0.    ]
 [0.     0.     0.18   2.     0.     0.    ]
 [0.     2.     0.04   1.     0.     1.    ]
 [0.     0.     0.24   2.     1.     0.    ]
 [1.     0.     0.25   0.     0.     1.    ]
 [0.     0.     0.19   0.     0.     0.    ]
 [0.     0.     0.36   2.     1.     1.    ]
 [0.     0.     0.15   0.     1.     1.    ]
 [0.     0.     0.18   0.     1.     1.    ]
 [0.     2.     0.09   0.     0.     1.    ]
 [0.     0.     0.28   2.     1.     1.    ]
 [0.     2.     0.18   2.     1.     1.    ]
 [0.     0.     0.17   2.     1.     1.    ]
 [1.     0.     0.29   2.     1.     1.    ]
 [1.     0.     0.23   1.     1.     1.    ]
 [0.     0.     0.28   2.     0.     0.    ]
 [1.     2.     0.36   1.     1.     1.    ]
 [0.     0.     0.18   2.     0.     0.    ]
 [0.     2.     0.41   0.     1.     0.    ]
 [0.     0.     0.27   0.     0.     0.    ]
 [0.     0.     0.26   0.     0.     1.    ]
 [0.     0.     0.455  1.     0.     0.    ]
 [4.     2.     0.06   0.     1.     0.    ]
 [1.     2.     0.25   2.     0.     0.    ]
 [0.     0.     0.19   0.     0.     0.    ]
 [0.     2.     0.22   1.     1.     1.    ]
 [0.     0.     0.16   1.     1.     1.    ]
 [0.     0.     0.19   0.     0.     0.    ]
 [0.     0.     0.235  0.     0.     0.    ]
 [1.     2.     0.22   2.     1.     1.    ]
 [1.     1.     0.34   2.     1.     1.    ]
 [0.     0.     0.71   1.     0.     0.    ]
 [0.     0.     0.19   1.     1.     1.    ]
 [0.     0.     0.36   2.     0.     0.    ]
 [0.     0.     0.42   0.     0.     0.    ]
 [0.     2.     0.18   1.     1.     1.    ]
 [0.     0.     0.14   0.     1.     0.    ]
 [0.     1.     0.06   2.     1.     1.    ]
 [0.     0.     0.29   0.     0.     0.    ]
 [0.     1.     0.27   0.     1.     1.    ]
 [0.     0.     0.62   1.     0.     0.    ]
 [0.     0.     0.25   0.     0.     0.    ]
 [1.     1.     0.6    2.     0.     0.    ]
 [0.     0.     0.36   1.     0.     1.    ]
 [1.     0.     0.29   2.     1.     1.    ]
 [0.     0.     0.34   2.     0.     0.    ]
 [3.     2.     0.09   0.     1.     0.    ]
 [0.     0.     0.19   0.     1.     1.    ]
 [0.     0.     0.16   0.     0.     0.    ]
 [0.     0.     0.31   2.     0.     1.    ]
 [0.     0.     0.4    2.     1.     1.    ]
 [1.     1.     0.09   0.     0.     1.    ]
 [1.     0.     0.31   0.     1.     0.    ]
 [0.     0.     0.38   2.     1.     0.    ]
 [0.     0.     0.17   2.     1.     1.    ]
 [0.     0.     0.28   2.     1.     1.    ]
 [1.     0.     0.5    1.     0.     0.    ]
 [0.     0.     0.62   1.     1.     1.    ]
 [1.     0.     0.25   2.     0.     0.    ]
 [0.     0.     0.3    1.     1.     1.    ]
 [1.     0.     0.28   0.     0.     0.    ]
 [0.     0.     0.35   0.     0.     0.    ]
 [1.     0.     0.42   1.     0.     1.    ]
 [0.     0.     0.39   0.     0.     0.    ]
 [1.     0.     0.25   1.     0.     1.    ]
 [0.     0.     0.38   1.     1.     1.    ]
 [0.     2.     0.29   0.     1.     1.    ]
 [4.     2.     0.04   0.     0.     0.    ]
 [0.     0.     0.18   0.     0.     0.    ]
 [0.     0.     0.56   1.     0.     0.    ]
 [0.     0.     0.26   2.     0.     0.    ]
 [0.     2.     0.19   1.     1.     1.    ]
 [0.     2.     0.36   1.     1.     1.    ]
 [1.     0.     0.18   0.     1.     0.    ]
 [1.     1.     0.16   0.     0.     0.    ]
 [0.     0.     0.35   1.     1.     1.    ]
 [0.     0.     0.22   1.     0.     0.    ]
 [0.     0.     0.35   0.     0.     0.    ]
 [0.     0.     0.21   0.     0.     0.    ]
 [0.     0.     0.2    0.     1.     0.    ]
 [1.     0.     0.26   0.     1.     0.    ]
 [0.     0.     0.5    2.     1.     1.    ]
 [0.     0.     0.28   0.     0.     0.    ]
 [0.     0.     0.16   0.     0.     0.    ]
 [0.     0.     0.45   1.     0.     0.    ]
 [2.     1.     0.01   2.     0.     1.    ]
 [4.     1.     0.16   0.     0.     0.    ]
 [0.     0.     0.51   0.     0.     0.    ]
 [2.     0.     0.53   1.     1.     1.    ]
 [1.     0.     0.49   1.     1.     1.    ]
 [0.     0.     0.305  0.     0.     0.    ]
 [3.     2.     0.19   1.     0.     0.    ]
 [0.     0.     0.23   2.     0.     0.    ]
 [0.     0.     0.22   0.     1.     1.    ]
 [0.     1.     0.02   0.     1.     1.    ]
 [0.     0.     0.24   2.     1.     1.    ]
 [0.     1.     0.54   1.     0.     0.    ]
 [0.     0.     0.23   0.     1.     0.    ]
 [3.     0.     0.33   0.     1.     1.    ]
 [0.     0.     0.16   0.     0.     0.    ]
 [1.     4.     0.4    0.     0.     0.    ]
 [0.     0.     0.3    0.     0.     0.    ]
 [3.     2.     0.24   1.     1.     1.    ]
 [0.     0.     0.58   1.     1.     1.    ]
 [1.     0.     0.44   2.     0.     0.    ]
 [0.     0.     0.46   1.     0.     0.    ]
 [0.     0.     0.38   0.     0.     0.    ]
 [1.     0.     0.18   1.     1.     1.    ]
 [0.     0.     0.15   0.     1.     1.    ]
 [1.     0.     0.26   0.     0.     0.    ]
 [0.     0.     0.31   0.     0.     0.    ]
 [0.     0.     0.22   0.     0.     0.    ]
 [0.     1.     0.16   1.     1.     1.    ]
 [1.     2.     0.03   2.     1.     1.    ]
 [1.     0.     0.22   0.     0.     0.    ]
 [1.     0.     0.14   0.     1.     1.    ]
 [0.     2.     0.17   1.     0.     1.    ]
 [0.     0.     0.28   2.     0.     0.    ]
 [0.     0.     0.18   0.     0.     0.    ]
 [1.     0.     0.48   1.     0.     1.    ]
 [0.     0.     0.24   1.     0.     0.    ]
 [3.     2.     0.04   0.     0.     0.    ]
 [0.     0.     0.41   1.     1.     1.    ]
 [1.     2.     0.05   2.     1.     1.    ]
 [0.     0.     0.22   0.     0.     0.    ]
 [0.     0.     0.21   1.     1.     1.    ]
 [0.     0.     0.42   1.     0.     1.    ]
 [0.     0.     0.16   0.     0.     1.    ]
 [0.     0.     0.17   0.     0.     0.    ]
 [0.     1.     0.37   1.     0.     0.    ]
 [1.     0.     0.27   2.     1.     0.    ]
 [0.     1.     0.0042 0.     0.     1.    ]
 [0.     0.     0.29   0.     0.     0.    ]
 [0.     0.     0.3    1.     1.     1.    ]
 [0.     0.     0.74   0.     0.     0.    ]
 [0.     0.     0.34   2.     1.     1.    ]
 [4.     1.     0.02   0.     0.     0.    ]
 [1.     1.     0.03   2.     0.     1.    ]
 [1.     1.     0.18   0.     0.     0.    ]
 [0.     0.     0.24   1.     1.     1.    ]
 [0.     0.     0.05   0.     1.     1.    ]]

## equis de test o prueba

In [40]:
X_test = test[:,0:5]

In [41]:
X_test

array([[1.    , 0.    , 0.48  , 1.    , 1.    ],
       [1.    , 0.    , 0.24  , 0.    , 1.    ],
       [0.    , 2.    , 0.405 , 0.    , 0.    ],
       [0.    , 0.    , 0.18  , 2.    , 0.    ],
       [0.    , 2.    , 0.04  , 1.    , 0.    ],
       [0.    , 0.    , 0.24  , 2.    , 1.    ],
       [1.    , 0.    , 0.25  , 0.    , 0.    ],
       [0.    , 0.    , 0.19  , 0.    , 0.    ],
       [0.    , 0.    , 0.36  , 2.    , 1.    ],
       [0.    , 0.    , 0.15  , 0.    , 1.    ],
       [0.    , 0.    , 0.18  , 0.    , 1.    ],
       [0.    , 2.    , 0.09  , 0.    , 0.    ],
       [0.    , 0.    , 0.28  , 2.    , 1.    ],
       [0.    , 2.    , 0.18  , 2.    , 1.    ],
       [0.    , 0.    , 0.17  , 2.    , 1.    ],
       [1.    , 0.    , 0.29  , 2.    , 1.    ],
       [1.    , 0.    , 0.23  , 1.    , 1.    ],
       [0.    , 0.    , 0.28  , 2.    , 0.    ],
       [1.    , 2.    , 0.36  , 1.    , 1.    ],
       [0.    , 0.    , 0.18  , 2.    , 0.    ],
       [0.    , 2.    , 0.41  , 0.    , 1.    ],
       [0.    , 0.    , 0.27  , 0.    , 0.    ],
       [0.    , 0.    , 0.26  , 0.    , 0.    ],
       [0.    , 0.    , 0.455 , 1.    , 0.    ],
       [4.    , 2.    , 0.06  , 0.    , 1.    ],
       [1.    , 2.    , 0.25  , 2.    , 0.    ],
       [0.    , 0.    , 0.19  , 0.    , 0.    ],
       [0.    , 2.    , 0.22  , 1.    , 1.    ],
       [0.    , 0.    , 0.16  , 1.    , 1.    ],
       [0.    , 0.    , 0.19  , 0.    , 0.    ],
       [0.    , 0.    , 0.235 , 0.    , 0.    ],
       [1.    , 2.    , 0.22  , 2.    , 1.    ],
       [1.    , 1.    , 0.34  , 2.    , 1.    ],
       [0.    , 0.    , 0.71  , 1.    , 0.    ],
       [0.    , 0.    , 0.19  , 1.    , 1.    ],
       [0.    , 0.    , 0.36  , 2.    , 0.    ],
       [0.    , 0.    , 0.42  , 0.    , 0.    ],
       [0.    , 2.    , 0.18  , 1.    , 1.    ],
       [0.    , 0.    , 0.14  , 0.    , 1.    ],
       [0.    , 1.    , 0.06  , 2.    , 1.    ],
       [0.    , 0.    , 0.29  , 0.    , 0.    ],
       [0.    , 1.    , 0.27  , 0.    , 1.    ],
       [0.    , 0.    , 0.62  , 1.    , 0.    ],
       [0.    , 0.    , 0.25  , 0.    , 0.    ],
       [1.    , 1.    , 0.6   , 2.    , 0.    ],
       [0.    , 0.    , 0.36  , 1.    , 0.    ],
       [1.    , 0.    , 0.29  , 2.    , 1.    ],
       [0.    , 0.    , 0.34  , 2.    , 0.    ],
       [3.    , 2.    , 0.09  , 0.    , 1.    ],
       [0.    , 0.    , 0.19  , 0.    , 1.    ],
       [0.    , 0.    , 0.16  , 0.    , 0.    ],
       [0.    , 0.    , 0.31  , 2.    , 0.    ],
       [0.    , 0.    , 0.4   , 2.    , 1.    ],
       [1.    , 1.    , 0.09  , 0.    , 0.    ],
       [1.    , 0.    , 0.31  , 0.    , 1.    ],
       [0.    , 0.    , 0.38  , 2.    , 1.    ],
       [0.    , 0.    , 0.17  , 2.    , 1.    ],
       [0.    , 0.    , 0.28  , 2.    , 1.    ],
       [1.    , 0.    , 0.5   , 1.    , 0.    ],
       [0.    , 0.    , 0.62  , 1.    , 1.    ],
       [1.    , 0.    , 0.25  , 2.    , 0.    ],
       [0.    , 0.    , 0.3   , 1.    , 1.    ],
       [1.    , 0.    , 0.28  , 0.    , 0.    ],
       [0.    , 0.    , 0.35  , 0.    , 0.    ],
       [1.    , 0.    , 0.42  , 1.    , 0.    ],
       [0.    , 0.    , 0.39  , 0.    , 0.    ],
       [1.    , 0.    , 0.25  , 1.    , 0.    ],
       [0.    , 0.    , 0.38  , 1.    , 1.    ],
       [0.    , 2.    , 0.29  , 0.    , 1.    ],
       [4.    , 2.    , 0.04  , 0.    , 0.    ],
       [0.    , 0.    , 0.18  , 0.    , 0.    ],
       [0.    , 0.    , 0.56  , 1.    , 0.    ],
       [0.    , 0.    , 0.26  , 2.    , 0.    ],
       [0.    , 2.    , 0.19  , 1.    , 1.    ],
       [0.    , 2.    , 0.36  , 1.    , 1.    ],
       [1.    , 0.    , 0.18  , 0.    , 1.    ],
       [1.    , 1.    , 0.16  , 0.    , 0.    ],
       [0.    , 0.    , 0.35  , 1.    , 1.    ],
       [0.    , 0.    , 0.22  , 1.    , 0.    ],
       [0.    , 0.    , 0.35  , 0.    , 0.    ],
       [0.    , 0.    , 0.21  , 0.    , 0.    ],
       [0.    , 0.    , 0.2   , 0.    , 1.    ],
       [1.    , 0.    , 0.26  , 0.    , 1.    ],
       [0.    , 0.    , 0.5   , 2.    , 1.    ],
       [0.    , 0.    , 0.28  , 0.    , 0.    ],
       [0.    , 0.    , 0.16  , 0.    , 0.    ],
       [0.    , 0.    , 0.45  , 1.    , 0.    ],
       [2.    , 1.    , 0.01  , 2.    , 0.    ],
       [4.    , 1.    , 0.16  , 0.    , 0.    ],
       [0.    , 0.    , 0.51  , 0.    , 0.    ],
       [2.    , 0.    , 0.53  , 1.    , 1.    ],
       [1.    , 0.    , 0.49  , 1.    , 1.    ],
       [0.    , 0.    , 0.305 , 0.    , 0.    ],
       [3.    , 2.    , 0.19  , 1.    , 0.    ],
       [0.    , 0.    , 0.23  , 2.    , 0.    ],
       [0.    , 0.    , 0.22  , 0.    , 1.    ],
       [0.    , 1.    , 0.02  , 0.    , 1.    ],
       [0.    , 0.    , 0.24  , 2.    , 1.    ],
       [0.    , 1.    , 0.54  , 1.    , 0.    ],
       [0.    , 0.    , 0.23  , 0.    , 1.    ],
       [3.    , 0.    , 0.33  , 0.    , 1.    ],
       [0.    , 0.    , 0.16  , 0.    , 0.    ],
       [1.    , 4.    , 0.4   , 0.    , 0.    ],
       [0.    , 0.    , 0.3   , 0.    , 0.    ],
       [3.    , 2.    , 0.24  , 1.    , 1.    ],
       [0.    , 0.    , 0.58  , 1.    , 1.    ],
       [1.    , 0.    , 0.44  , 2.    , 0.    ],
       [0.    , 0.    , 0.46  , 1.    , 0.    ],
       [0.    , 0.    , 0.38  , 0.    , 0.    ],
       [1.    , 0.    , 0.18  , 1.    , 1.    ],
       [0.    , 0.    , 0.15  , 0.    , 1.    ],
       [1.    , 0.    , 0.26  , 0.    , 0.    ],
       [0.    , 0.    , 0.31  , 0.    , 0.    ],
       [0.    , 0.    , 0.22  , 0.    , 0.    ],
       [0.    , 1.    , 0.16  , 1.    , 1.    ],
       [1.    , 2.    , 0.03  , 2.    , 1.    ],
       [1.    , 0.    , 0.22  , 0.    , 0.    ],
       [1.    , 0.    , 0.14  , 0.    , 1.    ],
       [0.    , 2.    , 0.17  , 1.    , 0.    ],
       [0.    , 0.    , 0.28  , 2.    , 0.    ],
       [0.    , 0.    , 0.18  , 0.    , 0.    ],
       [1.    , 0.    , 0.48  , 1.    , 0.    ],
       [0.    , 0.    , 0.24  , 1.    , 0.    ],
       [3.    , 2.    , 0.04  , 0.    , 0.    ],
       [0.    , 0.    , 0.41  , 1.    , 1.    ],
       [1.    , 2.    , 0.05  , 2.    , 1.    ],
       [0.    , 0.    , 0.22  , 0.    , 0.    ],
       [0.    , 0.    , 0.21  , 1.    , 1.    ],
       [0.    , 0.    , 0.42  , 1.    , 0.    ],
       [0.    , 0.    , 0.16  , 0.    , 0.    ],
       [0.    , 0.    , 0.17  , 0.    , 0.    ],
       [0.    , 1.    , 0.37  , 1.    , 0.    ],
       [1.    , 0.    , 0.27  , 2.    , 1.    ],
       [0.    , 1.    , 0.0042, 0.    , 0.    ],
       [0.    , 0.    , 0.29  , 0.    , 0.    ],
       [0.    , 0.    , 0.3   , 1.    , 1.    ],
       [0.    , 0.    , 0.74  , 0.    , 0.    ],
       [0.    , 0.    , 0.34  , 2.    , 1.    ],
       [4.    , 1.    , 0.02  , 0.    , 0.    ],
       [1.    , 1.    , 0.03  , 2.    , 0.    ],
       [1.    , 1.    , 0.18  , 0.    , 0.    ],
       [0.    , 0.    , 0.24  , 1.    , 1.    ],
       [0.    , 0.    , 0.05  , 0.    , 1.    ]])

In [43]:
pd.DataFrame(X_test).to_csv('X_pruebas.csv', header=False, index=False)

## yes de test o prueba

In [44]:
Y_test = test[:,5]

In [45]:
Y_test

array([1., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0.,
       1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1.,
       0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 1.])

In [47]:
pd.DataFrame(Y_test).to_csv('Y_pruebas.csv', header=False, index=False)

## Train validation

In [48]:
train, validation = train_test_split(train_vali, test_size=0.20) #, random_state=seem

## train

In [49]:
print("Rango: ", train.ndim)
print("Forma: ", train.shape)
print("Tipy: ", type(train))
print(train)

Rango:  2
Forma:  (456, 6)
Tipy:  <class 'numpy.ndarray'>
[[0.   0.   0.54 2.   0.   0.  ]
 [0.   0.   0.22 0.   0.   0.  ]
 [1.   0.   0.34 2.   0.   0.  ]
 ...
 [0.   1.   0.43 1.   1.   1.  ]
 [0.   0.   0.4  1.   0.   0.  ]
 [0.   0.   0.4  0.   0.   0.  ]]

## equis de train o etrenamiento

In [50]:
## features o x
X_train = train[:,0:5]

In [51]:
## extrayendo de la columna cero a la 4 
## se pone cinco ya que no es incluyente
print("Rango: ", X_train .ndim)
print("Forma: ", X_train .shape)
print("Tipy: ", type(X_train ))
print(X_train )

Rango:  2
Forma:  (456, 5)
Tipy:  <class 'numpy.ndarray'>
[[0.   0.   0.54 2.   0.  ]
 [0.   0.   0.22 0.   0.  ]
 [1.   0.   0.34 2.   0.  ]
 ...
 [0.   1.   0.43 1.   1.  ]
 [0.   0.   0.4  1.   0.  ]
 [0.   0.   0.4  0.   0.  ]]

## yes de train o entrenamiento

In [52]:
## Y 
## extrayendo solo la columna 5 que son las y, recordar que en pyton se cuenta a partir de cero
## 0, 1, 2, 3, 4, 5, 6
Y_train = train[:,5]
Y_train = Y_train.reshape(456,1)
print("Rango: ", Y_train.ndim)
print("Forma: ", Y_train.shape)
print("Tipy: ", type(Y_train))
print(Y_train)

Rango:  2
Forma:  (456, 1)
Tipy:  <class 'numpy.ndarray'>
[[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]]

## validation

In [53]:
print("Rango: ", validation.ndim)
print("Forma: ", validation.shape)
print("Tipy: ", type(validation))
print(validation)

Rango:  2
Forma:  (115, 6)
Tipy:  <class 'numpy.ndarray'>
[[0.     0.     0.42   0.     0.     0.    ]
 [0.     0.     0.27   2.     0.     0.    ]
 [0.     0.     0.23   2.     0.     0.    ]
 [0.     0.     0.32   0.     0.     1.    ]
 [0.     0.     0.21   2.     1.     1.    ]
 [1.     2.     0.33   2.     1.     1.    ]
 [0.     0.     0.19   0.     0.     0.    ]
 [0.     0.     0.41   0.     0.     0.    ]
 [0.     0.     0.3    0.     0.     0.    ]
 [0.     0.     0.45   1.     0.     1.    ]
 [0.     0.     0.21   0.     0.     0.    ]
 [0.     1.     0.23   1.     0.     1.    ]
 [0.     0.     0.59   2.     0.     0.    ]
 [0.     0.     0.22   0.     0.     0.    ]
 [0.     0.     0.35   2.     1.     1.    ]
 [0.     0.     0.55   2.     1.     1.    ]
 [0.     2.     0.04   0.     1.     1.    ]
 [0.     0.     0.6    1.     0.     0.    ]
 [4.     2.     0.09   0.     0.     0.    ]
 [2.     2.     0.21   1.     1.     1.    ]
 [1.     1.     0.4    2.     1.     1.    ]
 [2.     0.     0.41   0.     0.     0.    ]
 [0.     0.     0.26   0.     1.     1.    ]
 [0.     0.     0.22   0.     1.     0.    ]
 [0.     0.     0.18   0.     1.     0.    ]
 [1.     0.     0.28   1.     0.     0.    ]
 [0.     0.     0.19   2.     0.     0.    ]
 [0.     1.     0.5    2.     1.     1.    ]
 [0.     0.     0.36   2.     1.     1.    ]
 [0.     0.     0.3    0.     0.     0.    ]
 [1.     1.     0.0083 2.     0.     1.    ]
 [5.     2.     0.14   0.     0.     0.    ]
 [0.     0.     0.325  2.     1.     1.    ]
 [1.     0.     0.21   2.     0.     0.    ]
 [0.     0.     0.34   2.     0.     0.    ]
 [0.     0.     0.32   0.     0.     0.    ]
 [1.     0.     0.34   2.     0.     0.    ]
 [0.     0.     0.19   0.     0.     0.    ]
 [0.     0.     0.62   2.     0.     1.    ]
 [1.     0.     0.63   1.     1.     1.    ]
 [0.     0.     0.21   0.     0.     1.    ]
 [1.     1.     0.04   0.     1.     1.    ]
 [0.     0.     0.22   0.     1.     1.    ]
 [0.     0.     0.28   0.     0.     0.    ]
 [0.     0.     0.205  0.     0.     0.    ]
 [0.     0.     0.22   0.     1.     0.    ]
 [0.     0.     0.47   1.     0.     0.    ]
 [0.     0.     0.23   2.     1.     1.    ]
 [0.     0.     0.3    2.     1.     1.    ]
 [0.     0.     0.25   0.     0.     1.    ]
 [1.     1.     0.02   2.     0.     1.    ]
 [0.     1.     0.5    1.     1.     1.    ]
 [0.     0.     0.22   0.     0.     0.    ]
 [0.     0.     0.19   0.     0.     0.    ]
 [4.     2.     0.09   0.     1.     0.    ]
 [1.     0.     0.14   2.     1.     1.    ]
 [0.     0.     0.35   1.     0.     1.    ]
 [1.     1.     0.45   2.     1.     1.    ]
 [0.     0.     0.4    0.     0.     0.    ]
 [0.     0.     0.39   2.     0.     0.    ]
 [0.     1.     0.45   0.     1.     0.    ]
 [2.     0.     0.5    1.     0.     1.    ]
 [2.     1.     0.23   2.     0.     0.    ]
 [0.     0.     0.2    0.     0.     0.    ]
 [1.     2.     0.02   1.     1.     0.    ]
 [0.     2.     0.01   0.     1.     1.    ]
 [0.     0.     0.2    0.     0.     0.    ]
 [0.     0.     0.25   0.     0.     0.    ]
 [2.     0.     0.28   0.     0.     0.    ]
 [0.     0.     0.4    1.     0.     1.    ]
 [0.     2.     0.27   1.     0.     0.    ]
 [0.     0.     0.27   2.     1.     1.    ]
 [0.     0.     0.22   0.     0.     1.    ]
 [1.     0.     0.145  0.     1.     0.    ]
 [0.     0.     0.3    2.     0.     0.    ]
 [1.     1.     0.39   1.     1.     1.    ]
 [0.     0.     0.21   0.     0.     0.    ]
 [1.     0.     0.17   1.     1.     1.    ]
 [2.     0.     0.21   2.     0.     0.    ]
 [0.     0.     0.32   0.     0.     1.    ]
 [4.     1.     0.04   0.     0.     0.    ]
 [0.     0.     0.23   0.     0.     0.    ]
 [0.     0.     0.66   2.     0.     0.    ]
 [0.     0.     0.3    0.     1.     1.    ]
 [1.     1.     0.31   0.     1.     1.    ]
 [0.     2.     0.1    0.     1.     0.    ]
 [1.     1.     0.47   1.     1.     1.    ]
 [0.     1.     0.24   1.     0.     0.    ]
 [0.     0.     0.54   2.     0.     0.    ]
 [0.     1.     0.34   2.     1.     1.    ]
 [1.     0.     0.24   2.     1.     1.    ]
 [0.     0.     0.705  0.     0.     0.    ]
 [1.     0.     0.37   2.     0.     0.    ]
 [1.     0.     0.17   1.     1.     1.    ]
 [0.     0.     0.5    0.     0.     0.    ]
 [4.     2.     0.11   0.     1.     0.    ]
 [0.     0.     0.47   1.     0.     0.    ]
 [0.     0.     0.24   0.     0.     0.    ]
 [0.     0.     0.26   1.     0.     1.    ]
 [0.     0.     0.25   2.     0.     0.    ]
 [0.     0.     0.24   1.     1.     1.    ]
 [0.     0.     0.455  0.     0.     0.    ]
 [1.     1.     0.35   0.     1.     1.    ]
 [0.     0.     0.65   0.     0.     0.    ]
 [0.     0.     0.61   1.     0.     0.    ]
 [1.     0.     0.49   1.     0.     1.    ]
 [0.     2.     0.24   2.     1.     1.    ]
 [0.     0.     0.58   1.     0.     0.    ]
 [0.     0.     0.26   0.     0.     0.    ]
 [1.     1.     0.31   2.     0.     0.    ]
 [0.     0.     0.16   2.     0.     0.    ]
 [0.     0.     0.3    2.     0.     0.    ]
 [0.     0.     0.23   0.     1.     1.    ]
 [0.     0.     0.3    0.     0.     0.    ]
 [0.     0.     0.33   0.     0.     0.    ]]

## equis de validaci√≥n

In [54]:
X_validation = validation[:,0:5]

In [55]:
X_validation

array([[0.    , 0.    , 0.42  , 0.    , 0.    ],
       [0.    , 0.    , 0.27  , 2.    , 0.    ],
       [0.    , 0.    , 0.23  , 2.    , 0.    ],
       [0.    , 0.    , 0.32  , 0.    , 0.    ],
       [0.    , 0.    , 0.21  , 2.    , 1.    ],
       [1.    , 2.    , 0.33  , 2.    , 1.    ],
       [0.    , 0.    , 0.19  , 0.    , 0.    ],
       [0.    , 0.    , 0.41  , 0.    , 0.    ],
       [0.    , 0.    , 0.3   , 0.    , 0.    ],
       [0.    , 0.    , 0.45  , 1.    , 0.    ],
       [0.    , 0.    , 0.21  , 0.    , 0.    ],
       [0.    , 1.    , 0.23  , 1.    , 0.    ],
       [0.    , 0.    , 0.59  , 2.    , 0.    ],
       [0.    , 0.    , 0.22  , 0.    , 0.    ],
       [0.    , 0.    , 0.35  , 2.    , 1.    ],
       [0.    , 0.    , 0.55  , 2.    , 1.    ],
       [0.    , 2.    , 0.04  , 0.    , 1.    ],
       [0.    , 0.    , 0.6   , 1.    , 0.    ],
       [4.    , 2.    , 0.09  , 0.    , 0.    ],
       [2.    , 2.    , 0.21  , 1.    , 1.    ],
       [1.    , 1.    , 0.4   , 2.    , 1.    ],
       [2.    , 0.    , 0.41  , 0.    , 0.    ],
       [0.    , 0.    , 0.26  , 0.    , 1.    ],
       [0.    , 0.    , 0.22  , 0.    , 1.    ],
       [0.    , 0.    , 0.18  , 0.    , 1.    ],
       [1.    , 0.    , 0.28  , 1.    , 0.    ],
       [0.    , 0.    , 0.19  , 2.    , 0.    ],
       [0.    , 1.    , 0.5   , 2.    , 1.    ],
       [0.    , 0.    , 0.36  , 2.    , 1.    ],
       [0.    , 0.    , 0.3   , 0.    , 0.    ],
       [1.    , 1.    , 0.0083, 2.    , 0.    ],
       [5.    , 2.    , 0.14  , 0.    , 0.    ],
       [0.    , 0.    , 0.325 , 2.    , 1.    ],
       [1.    , 0.    , 0.21  , 2.    , 0.    ],
       [0.    , 0.    , 0.34  , 2.    , 0.    ],
       [0.    , 0.    , 0.32  , 0.    , 0.    ],
       [1.    , 0.    , 0.34  , 2.    , 0.    ],
       [0.    , 0.    , 0.19  , 0.    , 0.    ],
       [0.    , 0.    , 0.62  , 2.    , 0.    ],
       [1.    , 0.    , 0.63  , 1.    , 1.    ],
       [0.    , 0.    , 0.21  , 0.    , 0.    ],
       [1.    , 1.    , 0.04  , 0.    , 1.    ],
       [0.    , 0.    , 0.22  , 0.    , 1.    ],
       [0.    , 0.    , 0.28  , 0.    , 0.    ],
       [0.    , 0.    , 0.205 , 0.    , 0.    ],
       [0.    , 0.    , 0.22  , 0.    , 1.    ],
       [0.    , 0.    , 0.47  , 1.    , 0.    ],
       [0.    , 0.    , 0.23  , 2.    , 1.    ],
       [0.    , 0.    , 0.3   , 2.    , 1.    ],
       [0.    , 0.    , 0.25  , 0.    , 0.    ],
       [1.    , 1.    , 0.02  , 2.    , 0.    ],
       [0.    , 1.    , 0.5   , 1.    , 1.    ],
       [0.    , 0.    , 0.22  , 0.    , 0.    ],
       [0.    , 0.    , 0.19  , 0.    , 0.    ],
       [4.    , 2.    , 0.09  , 0.    , 1.    ],
       [1.    , 0.    , 0.14  , 2.    , 1.    ],
       [0.    , 0.    , 0.35  , 1.    , 0.    ],
       [1.    , 1.    , 0.45  , 2.    , 1.    ],
       [0.    , 0.    , 0.4   , 0.    , 0.    ],
       [0.    , 0.    , 0.39  , 2.    , 0.    ],
       [0.    , 1.    , 0.45  , 0.    , 1.    ],
       [2.    , 0.    , 0.5   , 1.    , 0.    ],
       [2.    , 1.    , 0.23  , 2.    , 0.    ],
       [0.    , 0.    , 0.2   , 0.    , 0.    ],
       [1.    , 2.    , 0.02  , 1.    , 1.    ],
       [0.    , 2.    , 0.01  , 0.    , 1.    ],
       [0.    , 0.    , 0.2   , 0.    , 0.    ],
       [0.    , 0.    , 0.25  , 0.    , 0.    ],
       [2.    , 0.    , 0.28  , 0.    , 0.    ],
       [0.    , 0.    , 0.4   , 1.    , 0.    ],
       [0.    , 2.    , 0.27  , 1.    , 0.    ],
       [0.    , 0.    , 0.27  , 2.    , 1.    ],
       [0.    , 0.    , 0.22  , 0.    , 0.    ],
       [1.    , 0.    , 0.145 , 0.    , 1.    ],
       [0.    , 0.    , 0.3   , 2.    , 0.    ],
       [1.    , 1.    , 0.39  , 1.    , 1.    ],
       [0.    , 0.    , 0.21  , 0.    , 0.    ],
       [1.    , 0.    , 0.17  , 1.    , 1.    ],
       [2.    , 0.    , 0.21  , 2.    , 0.    ],
       [0.    , 0.    , 0.32  , 0.    , 0.    ],
       [4.    , 1.    , 0.04  , 0.    , 0.    ],
       [0.    , 0.    , 0.23  , 0.    , 0.    ],
       [0.    , 0.    , 0.66  , 2.    , 0.    ],
       [0.    , 0.    , 0.3   , 0.    , 1.    ],
       [1.    , 1.    , 0.31  , 0.    , 1.    ],
       [0.    , 2.    , 0.1   , 0.    , 1.    ],
       [1.    , 1.    , 0.47  , 1.    , 1.    ],
       [0.    , 1.    , 0.24  , 1.    , 0.    ],
       [0.    , 0.    , 0.54  , 2.    , 0.    ],
       [0.    , 1.    , 0.34  , 2.    , 1.    ],
       [1.    , 0.    , 0.24  , 2.    , 1.    ],
       [0.    , 0.    , 0.705 , 0.    , 0.    ],
       [1.    , 0.    , 0.37  , 2.    , 0.    ],
       [1.    , 0.    , 0.17  , 1.    , 1.    ],
       [0.    , 0.    , 0.5   , 0.    , 0.    ],
       [4.    , 2.    , 0.11  , 0.    , 1.    ],
       [0.    , 0.    , 0.47  , 1.    , 0.    ],
       [0.    , 0.    , 0.24  , 0.    , 0.    ],
       [0.    , 0.    , 0.26  , 1.    , 0.    ],
       [0.    , 0.    , 0.25  , 2.    , 0.    ],
       [0.    , 0.    , 0.24  , 1.    , 1.    ],
       [0.    , 0.    , 0.455 , 0.    , 0.    ],
       [1.    , 1.    , 0.35  , 0.    , 1.    ],
       [0.    , 0.    , 0.65  , 0.    , 0.    ],
       [0.    , 0.    , 0.61  , 1.    , 0.    ],
       [1.    , 0.    , 0.49  , 1.    , 0.    ],
       [0.    , 2.    , 0.24  , 2.    , 1.    ],
       [0.    , 0.    , 0.58  , 1.    , 0.    ],
       [0.    , 0.    , 0.26  , 0.    , 0.    ],
       [1.    , 1.    , 0.31  , 2.    , 0.    ],
       [0.    , 0.    , 0.16  , 2.    , 0.    ],
       [0.    , 0.    , 0.3   , 2.    , 0.    ],
       [0.    , 0.    , 0.23  , 0.    , 1.    ],
       [0.    , 0.    , 0.3   , 0.    , 0.    ],
       [0.    , 0.    , 0.33  , 0.    , 0.    ]])

## yes de validaci√≥n

In [56]:
Y_validation = validation[:,5]
Y_validation = Y_validation.reshape(115,1)

In [57]:
Y_validation.shape

(115, 1)

## ¬øC√≥mo hacer boostrap?

## Partiendo de que se deben implementar 4 modelos, generaria 4 muestras del data set de entrenamiento y entrenaria cada modelo con su muestra correspondiente. 

## De sklearn.utils importaria resample, y generaria cuatro muestresa del data set de entremaniento que correpondera para cada modelo a implementar,

In [58]:
## generando archivo de excel para ir guardando los resultados 
import xlwt
from xlwt import Workbook 
wb = Workbook() 
sheet1 = wb.add_sheet('Sheet 1', cell_overwrite_ok=True)

In [59]:
## poniendo nombres en columnas
#sheet1.write(0, 1, 'Nombre del Modelo') 
sheet1.write(0, 1, 'Cadena de configuraci√≥n') 

sheet1.write(0, 2, 'Train Error') 
sheet1.write(0, 3, 'Train Accuracy') 
sheet1.write(0, 4, 'Train Precision')
sheet1.write(0, 5, 'Train Recall')
sheet1.write(0, 6, 'Train f1score')

sheet1.write(0, 7, 'Validation Error') 
sheet1.write(0, 8, 'Validation Accuracy') 
sheet1.write(0, 9, 'Validation Precision')
sheet1.write(0, 10, 'Validation Recall')
sheet1.write(0, 11, 'Validation f1score')
sheet1.write(0, 12, 'Modelo entrenado-Parametros')

## Arbol de decisi√≥n con sklearn

In [60]:
from sklearn import tree
from sklearn.metrics import brier_score_loss
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.externals import joblib ## libreria para poder escribrir, guardar o exportar los modelos al disco duro

## Funci√≥n para decisi√≥n tree

In [61]:
def train_tree(XT, YT, XV, YV,PASO):
    tree_model = tree.DecisionTreeClassifier(max_depth=PASO)
    tree_model = tree_model.fit(XT, YT) ## a esto le deberia de hacer return si quiero usar el modelo para predecir 
    
    Y_Train_predic = tree_model.predict(XT)
    Error_Train = brier_score_loss(YT, Y_Train_predic)
    Accuracy_Train = accuracy_score(YT, Y_Train_predic, normalize = True)
    Precision_Train = precision_score(YT, Y_Train_predic) 
    Recall_Train = recall_score(YT, Y_Train_predic)
    F1_Train = f1_score(YT, Y_Train_predic)
    
    Y_Validation_predic = tree_model.predict(XV)
    Error_Validation = brier_score_loss(YV, Y_Validation_predic)
    Accuracy_Validation = accuracy_score(YV, Y_Validation_predic, normalize = True)
    Precision_Validation = precision_score(YV, Y_Validation_predic)
    Recall_Validation = recall_score(YV, Y_Validation_predic)
    F1_Validation = f1_score(YV, Y_Validation_predic)

    cadena_config = "Decisiontree""_max_depth="+str(PASO)
    ##return final_W, final_B, cadena_config
    
    
    print("Cadena:", cadena_config)
    
    print("Error de Entrenamiento:", Error_Train)
    print("Error de Vallidaci√≤n:", Error_Validation)
    
    print("Accuracy de Entrenamiento:", Accuracy_Train)
    print("Accuracy de Vallidaci√≤n:", Accuracy_Validation)
    
    print("Precision de Entrenamiento:", Precision_Train)
    print("Precision de Vallidaci√≤n:", Precision_Validation)
    
    print("Recall de Entrenamiento:", Recall_Train)
    print("Recall de Vallidaci√≤n:", Recall_Validation)
    
    print("f1 score de Entrenamiento:", F1_Train)
    print("f1 score de Vallidaci√≤n:", F1_Validation)
    
    return cadena_config,Error_Train,Accuracy_Train,Precision_Train,Recall_Train,F1_Train,Error_Validation,Accuracy_Validation,Precision_Validation,Recall_Validation,F1_Validation,tree_model

In [62]:
tcc1,te1,ta1,tp1,tr1,tf1,te1v,ta1v,tp1v,tr1v,tf1v,d_t_modelo1 = train_tree(X_train, Y_train, X_validation, Y_validation,None)

Cadena: Decisiontree_max_depth=None
Error de Entrenamiento: 0.05482456140350877
Error de Vallidaci√≤n: 0.21739130434782608
Accuracy de Entrenamiento: 0.9451754385964912
Accuracy de Vallidaci√≤n: 0.782608695652174
Precision de Entrenamiento: 0.9806451612903225
Precision de Vallidaci√≤n: 0.7674418604651163
Recall de Entrenamiento: 0.8735632183908046
Recall de Vallidaci√≤n: 0.6875
f1 score de Entrenamiento: 0.9240121580547113
f1 score de Vallidaci√≤n: 0.7252747252747254

In [63]:
## prueba de predicci√≥n para una fila
## se hace reshape para que los datos entren bien al modelo
d_t_modelo1.predict(X_train[2].reshape((1, 5)))

array([0.])

In [64]:
##LLenado con valores la fila 1
sheet1.write(1, 1, tcc1) 
sheet1.write(1, 2, te1) 
sheet1.write(1, 3, ta1) 
sheet1.write(1, 4, tp1) 
sheet1.write(1, 5, tr1)
sheet1.write(1, 6, tf1)
sheet1.write(1, 7, te1v)
sheet1.write(1, 8, ta1v) 
sheet1.write(1, 9, tp1v) 
sheet1.write(1, 10, tr1v)
sheet1.write(1, 11, tf1v)
sheet1.write(1, 12, str(d_t_modelo1))

In [65]:
type(tcc1)

str

In [66]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
joblib.dump(d_t_modelo1, tcc1+".pkl")

['Decisiontree_max_depth=None.pkl']

In [67]:
tcc2,te2,ta2,tp2,tr2,tf2,te2v,ta2v,tp2v,tr2v,tf2v,d_t_modelo2 = train_tree(X_train, Y_train, X_validation, Y_validation,1)

Cadena: Decisiontree_max_depth=1
Error de Entrenamiento: 0.23026315789473684
Error de Vallidaci√≤n: 0.20869565217391303
Accuracy de Entrenamiento: 0.7697368421052632
Accuracy de Vallidaci√≤n: 0.7913043478260869
Precision de Entrenamiento: 0.7225806451612903
Precision de Vallidaci√≤n: 0.7857142857142857
Recall de Entrenamiento: 0.6436781609195402
Recall de Vallidaci√≤n: 0.6875
f1 score de Entrenamiento: 0.6808510638297872
f1 score de Vallidaci√≤n: 0.7333333333333334

In [68]:
##LLenado con valores la fila 2
sheet1.write(2, 1, tcc2) 
sheet1.write(2, 2, te2) 
sheet1.write(2, 3, ta2) 
sheet1.write(2, 4, tp2) 
sheet1.write(2, 5, tr2)
sheet1.write(2, 6, tf2)
sheet1.write(2, 7, te2v)
sheet1.write(2, 8, ta2v) 
sheet1.write(2, 9, tp2v) 
sheet1.write(2, 10, tr2v)
sheet1.write(2, 11, tf2v)
sheet1.write(2, 12, str(d_t_modelo2))

In [69]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
joblib.dump(d_t_modelo2, tcc2+".pkl")

['Decisiontree_max_depth=1.pkl']

In [70]:
tcc3,te3,ta3,tp3,tr3,tf3,te3v,ta3v,tp3v,tr3v,tf3v,d_t_modelo3 = train_tree(X_train, Y_train, X_validation, Y_validation,2)

Cadena: Decisiontree_max_depth=2
Error de Entrenamiento: 0.19078947368421054
Error de Vallidaci√≤n: 0.20869565217391303
Accuracy de Entrenamiento: 0.8092105263157895
Accuracy de Vallidaci√≤n: 0.7913043478260869
Precision de Entrenamiento: 0.9142857142857143
Precision de Vallidaci√≤n: 0.9285714285714286
Recall de Entrenamiento: 0.5517241379310345
Recall de Vallidaci√≤n: 0.5416666666666666
f1 score de Entrenamiento: 0.6881720430107526
f1 score de Vallidaci√≤n: 0.6842105263157894

In [71]:
##LLenado con valores la fila 3
sheet1.write(3, 1, tcc3) 
sheet1.write(3, 2, te3) 
sheet1.write(3, 3, ta3) 
sheet1.write(3, 4, tp3) 
sheet1.write(3, 5, tr3)
sheet1.write(3, 6, tf3)
sheet1.write(3, 7, te3v)
sheet1.write(3, 8, ta3v) 
sheet1.write(3, 9, tp3v) 
sheet1.write(3, 10, tr3v)
sheet1.write(3, 11, tf3v)
sheet1.write(3, 12, str(d_t_modelo3))

In [72]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
joblib.dump(d_t_modelo3, tcc3+".pkl")

['Decisiontree_max_depth=2.pkl']

In [73]:
tcc4,te4,ta4,tp4,tr4,tf4,te4v,ta4v,tp4v,tr4v,tf4v,d_t_modelo4 = train_tree(X_train, Y_train, X_validation, Y_validation,3)

Cadena: Decisiontree_max_depth=3
Error de Entrenamiento: 0.17763157894736842
Error de Vallidaci√≤n: 0.20869565217391303
Accuracy de Entrenamiento: 0.8223684210526315
Accuracy de Vallidaci√≤n: 0.7913043478260869
Precision de Entrenamiento: 0.8297872340425532
Precision de Vallidaci√≤n: 0.8
Recall de Entrenamiento: 0.6724137931034483
Recall de Vallidaci√≤n: 0.6666666666666666
f1 score de Entrenamiento: 0.7428571428571429
f1 score de Vallidaci√≤n: 0.7272727272727272

In [74]:
##LLenado con valores la fila 4
sheet1.write(4, 1, tcc4) 
sheet1.write(4, 2, te4) 
sheet1.write(4, 3, ta4) 
sheet1.write(4, 4, tp4) 
sheet1.write(4, 5, tr4)
sheet1.write(4, 6, tf4)
sheet1.write(4, 7, te4v)
sheet1.write(4, 8, ta4v) 
sheet1.write(4, 9, tp4v) 
sheet1.write(4, 10, tr4v)
sheet1.write(4, 11, tf4v)
sheet1.write(4, 12, str(d_t_modelo4))

In [75]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
joblib.dump(d_t_modelo4, tcc4+".pkl")

['Decisiontree_max_depth=3.pkl']

In [76]:
tcc5,te5,ta5,tp5,tr5,tf5,te5v,ta5v,tp5v,tr5v,tf5v,d_t_modelo5 = train_tree(X_train, Y_train, X_validation, Y_validation,4)

Cadena: Decisiontree_max_depth=4
Error de Entrenamiento: 0.16447368421052633
Error de Vallidaci√≤n: 0.2
Accuracy de Entrenamiento: 0.8355263157894737
Accuracy de Vallidaci√≤n: 0.8
Precision de Entrenamiento: 0.9024390243902439
Precision de Vallidaci√≤n: 0.8378378378378378
Recall de Entrenamiento: 0.6379310344827587
Recall de Vallidaci√≤n: 0.6458333333333334
f1 score de Entrenamiento: 0.7474747474747474
f1 score de Vallidaci√≤n: 0.7294117647058824

In [77]:
##LLenado con valores la fila 5
sheet1.write(5, 1, tcc5) 
sheet1.write(5, 2, te5) 
sheet1.write(5, 3, ta5) 
sheet1.write(5, 4, tp5) 
sheet1.write(5, 5, tr5)
sheet1.write(5, 6, tf5)
sheet1.write(5, 7, te5v)
sheet1.write(5, 8, ta5v) 
sheet1.write(5, 9, tp5v) 
sheet1.write(5, 10, tr5v)
sheet1.write(5, 11, tf5v)
sheet1.write(5, 12, str(d_t_modelo5))

In [78]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
joblib.dump(d_t_modelo5, tcc5+".pkl")

['Decisiontree_max_depth=4.pkl']

In [79]:
tcc6,te6,ta6,tp6,tr6,tf6,te6v,ta6v,tp6v,tr6v,tf6v,d_t_modelo6 = train_tree(X_train, Y_train, X_validation, Y_validation,5)

Cadena: Decisiontree_max_depth=5
Error de Entrenamiento: 0.14473684210526316
Error de Vallidaci√≤n: 0.20869565217391303
Accuracy de Entrenamiento: 0.8552631578947368
Accuracy de Vallidaci√≤n: 0.7913043478260869
Precision de Entrenamiento: 0.8506493506493507
Precision de Vallidaci√≤n: 0.7857142857142857
Recall de Entrenamiento: 0.7528735632183908
Recall de Vallidaci√≤n: 0.6875
f1 score de Entrenamiento: 0.7987804878048782
f1 score de Vallidaci√≤n: 0.7333333333333334

In [80]:
##LLenado con valores la fila 6
sheet1.write(6, 1, tcc6) 
sheet1.write(6, 2, te6) 
sheet1.write(6, 3, ta6) 
sheet1.write(6, 4, tp6) 
sheet1.write(6, 5, tr6)
sheet1.write(6, 6, tf6)
sheet1.write(6, 7, te6v)
sheet1.write(6, 8, ta6v) 
sheet1.write(6, 9, tp6v) 
sheet1.write(6, 10, tr6v)
sheet1.write(6, 11, tf6v)
sheet1.write(6, 12, str(d_t_modelo6))

In [81]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
joblib.dump(d_t_modelo6, tcc6+".pkl")

['Decisiontree_max_depth=5.pkl']

## SVM con sklearn

In [82]:
from sklearn import svm

## Funci√≥n para SVM

In [83]:
def train_svm(XT, YT, XV, YV,c):
    svm_model = svm.SVC(C=c)
    svm_model = svm_model.fit(XT, YT) ## a esto le deberia de hacer return si quiero usar el modelo para predecir
    
    Y_Train_predic = svm_model.predict(XT)
    Error_Train = brier_score_loss(YT, Y_Train_predic)
    Accuracy_Train = accuracy_score(YT, Y_Train_predic, normalize = True)
    Precision_Train = precision_score(YT, Y_Train_predic) 
    Recall_Train = recall_score(YT, Y_Train_predic)
    F1_train = f1_score(YT, Y_Train_predic)
    
    Y_Validation_predic = svm_model.predict(XV)
    Error_Validation = brier_score_loss(YV, Y_Validation_predic)
    Accuracy_Validation = accuracy_score(YV, Y_Validation_predic, normalize = True)
    Precision_Validation = precision_score(YV, Y_Validation_predic)
    Recall_Validation = recall_score(YV, Y_Validation_predic)
    F1_Validation = f1_score(YV, Y_Validation_predic)
    
    cadena_config = "SVM""_C="+str(c)
    ##return final_W, final_B, cadena_config
    
    
    print("Cadena:", cadena_config)
    
    print("Error de Entrenamiento:", Error_Train)
    print("Error de Vallidaci√≤n:", Error_Validation)
    
    print("Accuracy de Entrenamiento:", Accuracy_Train)
    print("Accuracy de Vallidaci√≤n:", Accuracy_Validation)
    
    print("Precision de Entrenamiento:", Precision_Train)
    print("Precision de Vallidaci√≤n:", Precision_Validation)
    
    print("Recall de Entrenamiento:", Recall_Train)
    print("Recall de Vallidaci√≤n:", Recall_Validation)
    
    print("f1 score de Entrenamiento:", F1_train)
    print("f1 score de Vallidaci√≤n:", F1_Validation)
    
    ##cadena_config = "regLog""_epochs="+str(epochs)+"_lr="+str(LR)+"_Lasso="+str(L1)+"_Ledge="+str(L2)
    ##return final_W, final_B, cadena_config
    
    return cadena_config,Error_Train,Accuracy_Train,Precision_Train,Recall_Train,F1_train,Error_Validation,Accuracy_Validation,Precision_Validation,Recall_Validation,F1_Validation,svm_model

In [84]:
svmcc1,svme1,svma1,svmp1,svmr1,svmf1,svme1v,svma1v,svmp1v,svmr1v,svmf1v,svm_modelo1 = train_svm(X_train, Y_train, X_validation, Y_validation,0.01)

C:\Users\Johnatan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Cadena: SVM_C=0.01
Error de Entrenamiento: 0.3815789473684211
Error de Vallidaci√≤n: 0.41739130434782606
Accuracy de Entrenamiento: 0.618421052631579
Accuracy de Vallidaci√≤n: 0.5826086956521739
Precision de Entrenamiento: 0.0
Precision de Vallidaci√≤n: 0.0
Recall de Entrenamiento: 0.0
Recall de Vallidaci√≤n: 0.0
f1 score de Entrenamiento: 0.0
f1 score de Vallidaci√≤n: 0.0

C:\Users\Johnatan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Johnatan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Johnatan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Johnatan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)

In [85]:
##LLenado con valores la fila 7
sheet1.write(7, 1, svmcc1) 
sheet1.write(7, 2, svme1) 
sheet1.write(7, 3, svma1) 
sheet1.write(7, 4, svmp1) 
sheet1.write(7, 5, svmr1)
sheet1.write(7, 6, svmf1)
sheet1.write(7, 7, svme1v)
sheet1.write(7, 8, svma1v) 
sheet1.write(7, 9, svmp1v) 
sheet1.write(7, 10, svmr1v)
sheet1.write(7, 11, svmf1v)
sheet1.write(7, 12, str(svm_modelo1))

In [86]:
## prueba de predicci√≥n para una fila
## se hace reshape para que los datos entren bien al modelo
svm_modelo1.predict(X_train[2].reshape((1, 5)))

array([0.])

In [87]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
joblib.dump(svm_modelo1, svmcc1+".pkl")

['SVM_C=0.01.pkl']

In [88]:
svmcc2,svme2,svma2,svmp2,svmr2,svmf2,svme2v,svma2v,svmp2v,svmr2v,svmf2v,svm_modelo2 = train_svm(X_train, Y_train, X_validation, Y_validation,0.1)

Cadena: SVM_C=0.1
Error de Entrenamiento: 0.21710526315789475
Error de Vallidaci√≤n: 0.19130434782608696
Accuracy de Entrenamiento: 0.7828947368421053
Accuracy de Vallidaci√≤n: 0.808695652173913
Precision de Entrenamiento: 0.7862595419847328
Precision de Vallidaci√≤n: 0.825
Recall de Entrenamiento: 0.5919540229885057
Recall de Vallidaci√≤n: 0.6875
f1 score de Entrenamiento: 0.6754098360655738
f1 score de Vallidaci√≤n: 0.75

C:\Users\Johnatan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [89]:
##LLenado con valores la fila 8
sheet1.write(8, 1, svmcc2) 
sheet1.write(8, 2, svme2) 
sheet1.write(8, 3, svma2) 
sheet1.write(8, 4, svmp2) 
sheet1.write(8, 5, svmr2)
sheet1.write(8, 6, svmf2)
sheet1.write(8, 7, svme2v)
sheet1.write(8, 8, svma2v) 
sheet1.write(8, 9, svmp2v) 
sheet1.write(8, 10, svmr2v)
sheet1.write(8, 11, svmf2v)
sheet1.write(8, 12, str(svm_modelo2))

In [90]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
joblib.dump(svm_modelo2, svmcc2+".pkl")

['SVM_C=0.1.pkl']

In [91]:
svmcc3,svme3,svma3,svmp3,svmr3,svmf3,svme3v,svma3v,svmp3v,svmr3v,svmf3v,svm_modelo3 = train_svm(X_train, Y_train, X_validation, Y_validation,1)

Cadena: SVM_C=1
Error de Entrenamiento: 0.20175438596491227
Error de Vallidaci√≤n: 0.21739130434782608
Accuracy de Entrenamiento: 0.7982456140350878
Accuracy de Vallidaci√≤n: 0.782608695652174
Precision de Entrenamiento: 0.8253968253968254
Precision de Vallidaci√≤n: 0.8108108108108109
Recall de Entrenamiento: 0.5977011494252874
Recall de Vallidaci√≤n: 0.625
f1 score de Entrenamiento: 0.6933333333333335
f1 score de Vallidaci√≤n: 0.7058823529411764

C:\Users\Johnatan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [92]:
##LLenado con valores la fila 9
sheet1.write(9, 1, svmcc3) 
sheet1.write(9, 2, svme3) 
sheet1.write(9, 3, svma3) 
sheet1.write(9, 4, svmp3) 
sheet1.write(9, 5, svmr3)
sheet1.write(9, 6, svmf3)
sheet1.write(9, 7, svme3v)
sheet1.write(9, 8, svma3v) 
sheet1.write(9, 9, svmp3v) 
sheet1.write(9, 10, svmr3v)
sheet1.write(9, 11, svmf3v)
sheet1.write(9, 12, str(svm_modelo3))

In [93]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
joblib.dump(svm_modelo3, svmcc3+".pkl")

['SVM_C=1.pkl']

In [94]:
svmcc4,svme4,svma4,svmp4,svmr4,svmf4,svme4v,svma4v,svmp4v,svmr4v,svmf4v,svm_modelo4 = train_svm(X_train, Y_train, X_validation, Y_validation,10)

Cadena: SVM_C=10
Error de Entrenamiento: 0.18201754385964913
Error de Vallidaci√≤n: 0.2
Accuracy de Entrenamiento: 0.8179824561403509
Accuracy de Vallidaci√≤n: 0.8
Precision de Entrenamiento: 0.9252336448598131
Precision de Vallidaci√≤n: 0.9032258064516129
Recall de Entrenamiento: 0.5689655172413793
Recall de Vallidaci√≤n: 0.5833333333333334
f1 score de Entrenamiento: 0.7046263345195729
f1 score de Vallidaci√≤n: 0.7088607594936709

C:\Users\Johnatan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [95]:
##LLenado con valores la fila 10
sheet1.write(10, 1, svmcc4) 
sheet1.write(10, 2, svme4) 
sheet1.write(10, 3, svma4) 
sheet1.write(10, 4, svmp4) 
sheet1.write(10, 5, svmr4)
sheet1.write(10, 6, svmf4)
sheet1.write(10, 7, svme4v)
sheet1.write(10, 8, svma4v) 
sheet1.write(10, 9, svmp4v) 
sheet1.write(10, 10, svmr4v)
sheet1.write(10, 11, svmf4v)
sheet1.write(10, 12, str(svm_modelo4))

In [96]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
joblib.dump(svm_modelo4, svmcc4+".pkl")

['SVM_C=10.pkl']

In [97]:
svmcc5,svme5,svma5,svmp5,svmr5,svmf5,svme5v,svma5v,svmp5v,svmr5v,svmf5v,svm_modelo5 = train_svm(X_train, Y_train, X_validation, Y_validation,100)

Cadena: SVM_C=100
Error de Entrenamiento: 0.16447368421052633
Error de Vallidaci√≤n: 0.22608695652173913
Accuracy de Entrenamiento: 0.8355263157894737
Accuracy de Vallidaci√≤n: 0.7739130434782608
Precision de Entrenamiento: 0.9090909090909091
Precision de Vallidaci√≤n: 0.8055555555555556
Recall de Entrenamiento: 0.632183908045977
Recall de Vallidaci√≤n: 0.6041666666666666
f1 score de Entrenamiento: 0.7457627118644067
f1 score de Vallidaci√≤n: 0.6904761904761905

C:\Users\Johnatan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [98]:
##LLenado con valores la fila 11
sheet1.write(11, 1, svmcc5) 
sheet1.write(11, 2, svme5) 
sheet1.write(11, 3, svma5) 
sheet1.write(11, 4, svmp5) 
sheet1.write(11, 5, svmr5)
sheet1.write(11, 6, svmf5)
sheet1.write(11, 7, svme5v)
sheet1.write(11, 8, svma5v) 
sheet1.write(11, 9, svmp5v) 
sheet1.write(11, 10, svmr5v)
sheet1.write(11, 11, svmf5v)
sheet1.write(11, 12, str(svm_modelo5))

In [99]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
joblib.dump(svm_modelo5, svmcc5+".pkl")

['SVM_C=100.pkl']

## Regresi√≥n logistica binaria (sigmoid) en Tensorflow con regularizaci√≥n

### vector de unos

In [100]:
## como Y tiene la forma de rango uno
## se pasara a rango dos para luego poder hacer la insercion verticual
unos = np.ones_like(Y_train).reshape(456,1)
print("Tipo", type(unos))
print("Forma", unos.shape)
print("Rango", unos.ndim)
print("Vista de los datos", unos)

Tipo <class 'numpy.ndarray'>
Forma (456, 1)
Rango 2
Vista de los datos [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

### Nueva matriz

In [101]:
X1_train = np.hstack((unos,X_train))
print("Tipo", type(X1_train))
print("Forma", X1_train.shape)
print("Rango", X1_train.ndim)
print("Vista de los datos", X1_train)

Tipo <class 'numpy.ndarray'>
Forma (456, 6)
Rango 2
Vista de los datos [[1.   0.   0.   0.54 2.   0.  ]
 [1.   0.   0.   0.22 0.   0.  ]
 [1.   1.   0.   0.34 2.   0.  ]
 ...
 [1.   0.   1.   0.43 1.   1.  ]
 [1.   0.   0.   0.4  1.   0.  ]
 [1.   0.   0.   0.4  0.   0.  ]]

In [102]:
Y1_train = Y_train.reshape(456,1)
print("Tipo", type(Y1_train))
print("Forma", Y1_train.shape)
print("Rango", Y1_train.ndim)
print("Vista de los datos", Y1_train)

Tipo <class 'numpy.ndarray'>
Forma (456, 1)
Rango 2
Vista de los datos [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]]

## batches e hiperparametros

In [103]:
lr = 0.01
epochs = 20
batch_size = 32
batches = int(X_train.shape[0] / batch_size) ## extrae el numero de filas del dataset

## grafo

In [104]:
grafologistica = tf.Graph()
with grafologistica.as_default():
    
    with tf.name_scope("Declaring_placeholder"):    
        ## definiendo las X, 6 es el valor pues 6 son las x features luego del reshape 
        X = tf.placeholder(tf.float32, [None,5], name="X")
    
        ## definiendo las Y
        Y = tf.placeholder(tf.float32, [None,1], name="Y")
    
        ## estableciendo el learning rate placeholder
        ph_lr = tf.placeholder(dtype = tf.float64, name="LR")
        
        ## establenciend el valor de lamda para l1 y l2
        l1_g = tf.placeholder(dtype = tf.float32, name="L1")
        l2_g = tf.placeholder(dtype = tf.float32, name="L2")
        
    
    with tf.name_scope("Declaring_variables"):
        ## vector de parametros 
        W = tf.Variable(tf.zeros([5,1]), name = "W")
        B = tf.Variable(0, name = "b", dtype="float")
    
    with tf.name_scope("hipotesis"):   
        ## caculando los logits
        logits_g = tf.add(tf.matmul(X, W, name="hipotesis_producto_punto"), B, name="hipotesis_sumar_B")
    
        ## obteniendo las yhat pasando los logits por sigmoid
        ## esta sire para predecir
        yhat_g = tf.nn.sigmoid(logits_g, name="sigmoid")
    
    with tf.name_scope("funcion_costo"):
        ## calculando la fucion de costo con la entropia cruzada
        ## esta srive para entrenar
        cost_g = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits = logits_g, labels = Y))+tf.multiply(tf.reduce_sum(tf.abs(W)),l1_g)+tf.multiply(tf.reduce_sum(tf.pow(W,2)),l2_g) 
        ##aca tengo que poner la regularizacion lasso o ridge
        ##aca tengo que poner la regularizacion lasso o ridge [lamda * tf.sum(tf.abs(w),vertical axis =1)]
    
    with tf.name_scope("Gradient_Des.Optimizer"):
        ## gradient descent para optimizar un nodo mas del grafo
        optimizacion = tf.train.GradientDescentOptimizer(ph_lr).minimize(cost_g)
               
    ## accuracy a pie o a mano 
    correct_prediction = tf.equal(tf.cast(tf.greater_equal(yhat_g,0.5),tf.float32), Y)
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32)) ##media de los aciertos me da el accuracy
    
    ## metricas con tensor flow
    yhat_g_cerouno = tf.cast(tf.greater_equal(yhat_g,0.5),tf.float32)
    
    
    precision_g = tf.metrics.precision(Y, yhat_g_cerouno)
    recall_g = tf.metrics.recall(Y, yhat_g_cerouno)
    #f1_g = tf.metrics.f1_score(Y, yhat_g_cerouno)

In [105]:
def train_logistica(XT, YT, XV, YV, epochs=20, LR=0.1, L1=0, L2=0):
    with tf.Session(graph = grafologistica) as session:
        # incializando variables
        tf.global_variables_initializer().run()
        tf.local_variables_initializer().run() #esto se puso para que corriera el accuracy de tensorflow
        print('Initialized')
    
        for epoch in range(epochs):
            for i in range(batches):
                offset = i * epoch 
                x = XT[offset: offset + batch_size] ## slicing de filas
                y = YT[offset: offset + batch_size] ## slicing de filas
                _, final_W, final_B, train_accuracy, _yhatrain = session.run([optimizacion, W, B, accuracy, yhat_g_cerouno], 
                                                                  feed_dict={X:x, Y:y, ph_lr:LR, l1_g:L1, l2_g:L2})
                
                cost_s = session.run(cost_g, feed_dict={X:x, Y:y, ph_lr:LR, l1_g:L1, l2_g:L2})
                                                          
            if (epoch % 1 == 0):
                print("Iteraci√≥n en entrenamiento:", epoch, " Costo en entranmiento:", cost_s)
        
        print("Accuracy de entrenamiento:", train_accuracy)
        #print("accuracy_t:", accuracy_t)
    
        ## usando el grafo con otros datos 
        errorvalida, accuracyvalida, _yhatvalida = session.run([cost_g, accuracy, yhat_g_cerouno], 
                                                               feed_dict={X:XV, Y:YV, l1_g:L1, l2_g:L2})
        print("Costo en validaci√≥n:", errorvalida)
        print("Accuracy de validaci√≥n:", accuracyvalida)
            
    #Cadena de configuraci√≤n
    cadena_config = "regLog""_epochs="+str(epochs)+"_lr="+str(LR)+"_Lasso="+str(L1)+"_Ledge="+str(L2)
    
    ## metricas en entrenamiento 
    Precision_Train = precision_score(y, _yhatrain) 
    Recall_Train = recall_score(y, _yhatrain)
    F1_Train = f1_score(y, _yhatrain)
    
    ## metricas en validacion
    Precision_Validation = precision_score(YV, _yhatvalida) 
    Recall_Validation = recall_score(YV, _yhatvalida)
    F1_Validation = f1_score(YV, _yhatvalida)
        
    
    return cadena_config,cost_s,train_accuracy,Precision_Train,Recall_Train,F1_Train,errorvalida,accuracyvalida,Precision_Validation,Recall_Validation,F1_Validation,final_W, final_B,

In [106]:
reglogcc1,regloge1,regloga1,reglogp1,reglogr1,reglogf1,regloge1v,regloga1v,reglogp1v,reglogr1v,reglogf1v,W1,B1 = train_logistica(XT=X_train, YT=Y_train, XV=X_validation, YV=Y_validation, epochs=20, LR=10, L1=0, L2=0)

Initialized
Iteraci√≥n en entrenamiento: 0  Costo en entranmiento: 1.1208612
Iteraci√≥n en entrenamiento: 1  Costo en entranmiento: 0.34608257
Iteraci√≥n en entrenamiento: 2  Costo en entranmiento: 0.53815794
Iteraci√≥n en entrenamiento: 3  Costo en entranmiento: 1.8864926
Iteraci√≥n en entrenamiento: 4  Costo en entranmiento: 2.9605772
Iteraci√≥n en entrenamiento: 5  Costo en entranmiento: 1.4679623
Iteraci√≥n en entrenamiento: 6  Costo en entranmiento: 0.9174318
Iteraci√≥n en entrenamiento: 7  Costo en entranmiento: 1.3128097
Iteraci√≥n en entrenamiento: 8  Costo en entranmiento: 2.241567
Iteraci√≥n en entrenamiento: 9  Costo en entranmiento: 1.3319154
Iteraci√≥n en entrenamiento: 10  Costo en entranmiento: 0.37129742
Iteraci√≥n en entrenamiento: 11  Costo en entranmiento: 1.0496848
Iteraci√≥n en entrenamiento: 12  Costo en entranmiento: 1.09649
Iteraci√≥n en entrenamiento: 13  Costo en entranmiento: 1.0187718
Iteraci√≥n en entrenamiento: 14  Costo en entranmiento: 1.5149174
Iteraci√≥n en entrenamiento: 15  Costo en entranmiento: 1.0588427
Iteraci√≥n en entrenamiento: 16  Costo en entranmiento: 1.5128868
Iteraci√≥n en entrenamiento: 17  Costo en entranmiento: 0.67086285
Iteraci√≥n en entrenamiento: 18  Costo en entranmiento: 0.5974047
Iteraci√≥n en entrenamiento: 19  Costo en entranmiento: 0.7161406
Accuracy de entrenamiento: 0.6875
Costo en validaci√≥n: 0.6902648
Accuracy de validaci√≥n: 0.67826086

In [107]:
W1.shape

(5, 1)

In [108]:
B1.ndim

0

In [109]:
regloga1v

0.67826086

In [110]:
##LLenado con valores la fila 12
sheet1.write(12, 1, reglogcc1) 
sheet1.write(12, 2, str(regloge1)) 
sheet1.write(12, 3, str(regloga1)) 
sheet1.write(12, 4, str(reglogp1))
sheet1.write(12, 5, str(reglogr1))
sheet1.write(12, 6, str(reglogf1))
sheet1.write(12, 7, str(regloge1v))
sheet1.write(12, 8, str(regloga1v)) 
sheet1.write(12, 9, str(reglogp1v)) 
sheet1.write(12, 10, str(reglogr1v))
sheet1.write(12, 11, str(reglogf1v))
sheet1.write(12, 12, "W = "+str(W1)+" B = "+str(B1))

In [111]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
joblib.dump([W1,B1], reglogcc1+".pkl")

['regLog_epochs=20_lr=10_Lasso=0_Ledge=0.pkl']

In [112]:
reglogcc2,regloge2,regloga2,reglogp2,reglogr2,reglogf2,regloge2v,regloga2v,reglogp2v,reglogr2v,reglogf2v,W2,B2 = train_logistica(XT=X_train, YT=Y_train, XV=X_validation, YV=Y_validation, epochs=20, LR=1, L1=0, L2=0)

Initialized
Iteraci√≥n en entrenamiento: 0  Costo en entranmiento: 0.50566936
Iteraci√≥n en entrenamiento: 1  Costo en entranmiento: 0.36466628
Iteraci√≥n en entrenamiento: 2  Costo en entranmiento: 0.55910516
Iteraci√≥n en entrenamiento: 3  Costo en entranmiento: 0.66733134
Iteraci√≥n en entrenamiento: 4  Costo en entranmiento: 0.62987435
Iteraci√≥n en entrenamiento: 5  Costo en entranmiento: 0.520731
Iteraci√≥n en entrenamiento: 6  Costo en entranmiento: 0.4973745
Iteraci√≥n en entrenamiento: 7  Costo en entranmiento: 0.5410587
Iteraci√≥n en entrenamiento: 8  Costo en entranmiento: 0.5539248
Iteraci√≥n en entrenamiento: 9  Costo en entranmiento: 0.46675217
Iteraci√≥n en entrenamiento: 10  Costo en entranmiento: 0.34304416
Iteraci√≥n en entrenamiento: 11  Costo en entranmiento: 0.6630118
Iteraci√≥n en entrenamiento: 12  Costo en entranmiento: 0.8012285
Iteraci√≥n en entrenamiento: 13  Costo en entranmiento: 0.7043073
Iteraci√≥n en entrenamiento: 14  Costo en entranmiento: 0.52626234
Iteraci√≥n en entrenamiento: 15  Costo en entranmiento: 0.46468943
Iteraci√≥n en entrenamiento: 16  Costo en entranmiento: 0.47039574
Iteraci√≥n en entrenamiento: 17  Costo en entranmiento: 0.47091302
Iteraci√≥n en entrenamiento: 18  Costo en entranmiento: 0.53818315
Iteraci√≥n en entrenamiento: 19  Costo en entranmiento: 0.5587163
Accuracy de entrenamiento: 0.75
Costo en validaci√≥n: 0.50089836
Accuracy de validaci√≥n: 0.8086957

In [113]:
##LLenado con valores la fila 13
sheet1.write(13, 1, reglogcc2) 
sheet1.write(13, 2, str(regloge2)) 
sheet1.write(13, 3, str(regloga2)) 
sheet1.write(13, 4, str(reglogp2))
sheet1.write(13, 5, str(reglogr2))
sheet1.write(13, 6, str(reglogf2))
sheet1.write(13, 7, str(regloge2v))
sheet1.write(13, 8, str(regloga2v)) 
sheet1.write(13, 9, str(reglogp2v)) 
sheet1.write(13, 10, str(reglogr2v))
sheet1.write(13, 11, str(reglogf2v))
sheet1.write(13, 12, "W = "+str(W2)+" B = "+str(B2))

In [114]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
joblib.dump([W2,B2], reglogcc2+".pkl")

['regLog_epochs=20_lr=1_Lasso=0_Ledge=0.pkl']

In [115]:
reglogcc3,regloge3,regloga3,reglogp3,reglogr3,reglogf3,regloge3v,regloga3v,reglogp3v,reglogr3v,reglogf3v,W3,B3 = train_logistica(XT=X_train, YT=Y_train, XV=X_validation, YV=Y_validation, epochs=20, LR=0.1, L1=0, L2=0)

Initialized
Iteraci√≥n en entrenamiento: 0  Costo en entranmiento: 0.63593477
Iteraci√≥n en entrenamiento: 1  Costo en entranmiento: 0.58010495
Iteraci√≥n en entrenamiento: 2  Costo en entranmiento: 0.6195481
Iteraci√≥n en entrenamiento: 3  Costo en entranmiento: 0.6733836
Iteraci√≥n en entrenamiento: 4  Costo en entranmiento: 0.6716152
Iteraci√≥n en entrenamiento: 5  Costo en entranmiento: 0.65058076
Iteraci√≥n en entrenamiento: 6  Costo en entranmiento: 0.61252093
Iteraci√≥n en entrenamiento: 7  Costo en entranmiento: 0.5829754
Iteraci√≥n en entrenamiento: 8  Costo en entranmiento: 0.5887588
Iteraci√≥n en entrenamiento: 9  Costo en entranmiento: 0.55597377
Iteraci√≥n en entrenamiento: 10  Costo en entranmiento: 0.46830034
Iteraci√≥n en entrenamiento: 11  Costo en entranmiento: 0.63700974
Iteraci√≥n en entrenamiento: 12  Costo en entranmiento: 0.74906933
Iteraci√≥n en entrenamiento: 13  Costo en entranmiento: 0.70552
Iteraci√≥n en entrenamiento: 14  Costo en entranmiento: 0.58995104
Iteraci√≥n en entrenamiento: 15  Costo en entranmiento: 0.5498837
Iteraci√≥n en entrenamiento: 16  Costo en entranmiento: 0.52163106
Iteraci√≥n en entrenamiento: 17  Costo en entranmiento: 0.5220527
Iteraci√≥n en entrenamiento: 18  Costo en entranmiento: 0.5763348
Iteraci√≥n en entrenamiento: 19  Costo en entranmiento: 0.6190059
Accuracy de entrenamiento: 0.6875
Costo en validaci√≥n: 0.5305722
Accuracy de validaci√≥n: 0.76521736

In [116]:
##LLenado con valores la fila 14
sheet1.write(14, 1, reglogcc3) 
sheet1.write(14, 2, str(regloge3)) 
sheet1.write(14, 3, str(regloga3)) 
sheet1.write(14, 4, str(reglogp3))
sheet1.write(14, 5, str(reglogr3))
sheet1.write(14, 6, str(reglogf3))
sheet1.write(14, 7, str(regloge3v))
sheet1.write(14, 8, str(regloga3v)) 
sheet1.write(14, 9, str(reglogp3v)) 
sheet1.write(14, 10, str(reglogr3v))
sheet1.write(14, 11, str(reglogf3v))
sheet1.write(14, 12, "W = "+str(W3)+" B = "+str(B3))

In [117]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
joblib.dump([W3,B3], reglogcc3+".pkl")

['regLog_epochs=20_lr=0.1_Lasso=0_Ledge=0.pkl']

In [118]:
reglogcc4,regloge4,regloga4,reglogp4,reglogr4,reglogf4,regloge4v,regloga4v,reglogp4v,reglogr4v,reglogf4v,W4,B4 = train_logistica(XT=X_train, YT=Y_train, XV=X_validation, YV=Y_validation, epochs=20, LR=0.01, L1=0, L2=0)

Initialized
Iteraci√≥n en entrenamiento: 0  Costo en entranmiento: 0.6841541
Iteraci√≥n en entrenamiento: 1  Costo en entranmiento: 0.6757767
Iteraci√≥n en entrenamiento: 2  Costo en entranmiento: 0.6818988
Iteraci√≥n en entrenamiento: 3  Costo en entranmiento: 0.6892475
Iteraci√≥n en entrenamiento: 4  Costo en entranmiento: 0.6922643
Iteraci√≥n en entrenamiento: 5  Costo en entranmiento: 0.701149
Iteraci√≥n en entrenamiento: 6  Costo en entranmiento: 0.69793135
Iteraci√≥n en entrenamiento: 7  Costo en entranmiento: 0.6814368
Iteraci√≥n en entrenamiento: 8  Costo en entranmiento: 0.6782651
Iteraci√≥n en entrenamiento: 9  Costo en entranmiento: 0.66080797
Iteraci√≥n en entrenamiento: 10  Costo en entranmiento: 0.64539653
Iteraci√≥n en entrenamiento: 11  Costo en entranmiento: 0.66774476
Iteraci√≥n en entrenamiento: 12  Costo en entranmiento: 0.6932332
Iteraci√≥n en entrenamiento: 13  Costo en entranmiento: 0.69287384
Iteraci√≥n en entrenamiento: 14  Costo en entranmiento: 0.6690146
Iteraci√≥n en entrenamiento: 15  Costo en entranmiento: 0.65754044
Iteraci√≥n en entrenamiento: 16  Costo en entranmiento: 0.65009916
Iteraci√≥n en entrenamiento: 17  Costo en entranmiento: 0.6476591
Iteraci√≥n en entrenamiento: 18  Costo en entranmiento: 0.65843415
Iteraci√≥n en entrenamiento: 19  Costo en entranmiento: 0.6711346
Accuracy de entrenamiento: 0.5625
Costo en validaci√≥n: 0.6465783
Accuracy de validaci√≥n: 0.6869565

In [119]:
##LLenado con valores la fila 15
sheet1.write(15, 1, reglogcc4) 
sheet1.write(15, 2, str(regloge4)) 
sheet1.write(15, 3, str(regloga4)) 
sheet1.write(15, 4, str(reglogp4))
sheet1.write(15, 5, str(reglogr4))
sheet1.write(15, 6, str(reglogf4))
sheet1.write(15, 7, str(regloge4v))
sheet1.write(15, 8, str(regloga4v)) 
sheet1.write(15, 9, str(reglogp4v)) 
sheet1.write(15, 10, str(reglogr4v))
sheet1.write(15, 11, str(reglogf4v))
sheet1.write(15, 12, "W = "+str(W4)+" B = "+str(B4))

In [120]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
joblib.dump([W4,B4], reglogcc4+".pkl")

['regLog_epochs=20_lr=0.01_Lasso=0_Ledge=0.pkl']

In [121]:
reglogcc5,regloge5,regloga5,reglogp5,reglogr5,reglogf5,regloge5v,regloga5v,reglogp5v,reglogr5v,reglogf5v,W5,B5 = train_logistica(XT=X_train, YT=Y_train, XV=X_validation, YV=Y_validation, epochs=20, LR=1, L1=0.001, L2=0)

Initialized
Iteraci√≥n en entrenamiento: 0  Costo en entranmiento: 0.5088279
Iteraci√≥n en entrenamiento: 1  Costo en entranmiento: 0.36981553
Iteraci√≥n en entrenamiento: 2  Costo en entranmiento: 0.5632674
Iteraci√≥n en entrenamiento: 3  Costo en entranmiento: 0.6713169
Iteraci√≥n en entrenamiento: 4  Costo en entranmiento: 0.6337425
Iteraci√≥n en entrenamiento: 5  Costo en entranmiento: 0.52561754
Iteraci√≥n en entrenamiento: 6  Costo en entranmiento: 0.5023945
Iteraci√≥n en entrenamiento: 7  Costo en entranmiento: 0.54598486
Iteraci√≥n en entrenamiento: 8  Costo en entranmiento: 0.55850405
Iteraci√≥n en entrenamiento: 9  Costo en entranmiento: 0.47227412
Iteraci√≥n en entrenamiento: 10  Costo en entranmiento: 0.35058448
Iteraci√≥n en entrenamiento: 11  Costo en entranmiento: 0.66504866
Iteraci√≥n en entrenamiento: 12  Costo en entranmiento: 0.80208546
Iteraci√≥n en entrenamiento: 13  Costo en entranmiento: 0.7063451
Iteraci√≥n en entrenamiento: 14  Costo en entranmiento: 0.53006774
Iteraci√≥n en entrenamiento: 15  Costo en entranmiento: 0.46917796
Iteraci√≥n en entrenamiento: 16  Costo en entranmiento: 0.4732959
Iteraci√≥n en entrenamiento: 17  Costo en entranmiento: 0.4744783
Iteraci√≥n en entrenamiento: 18  Costo en entranmiento: 0.5418463
Iteraci√≥n en entrenamiento: 19  Costo en entranmiento: 0.566909
Accuracy de entrenamiento: 0.75
Costo en validaci√≥n: 0.5056715
Accuracy de validaci√≥n: 0.8086957

In [122]:
##LLenado con valores la fila 16
sheet1.write(16, 1, reglogcc5) 
sheet1.write(16, 2, str(regloge5)) 
sheet1.write(16, 3, str(regloga5)) 
sheet1.write(16, 4, str(reglogp5))
sheet1.write(16, 5, str(reglogr5))
sheet1.write(16, 6, str(reglogf5))
sheet1.write(16, 7, str(regloge5v))
sheet1.write(16, 8, str(regloga5v)) 
sheet1.write(16, 9, str(reglogp5v)) 
sheet1.write(16, 10, str(reglogr5v))
sheet1.write(16, 11, str(reglogf5v))
sheet1.write(16, 12, "W = "+str(W5)+" B = "+str(B5))

In [123]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
joblib.dump([W5,B5], reglogcc5+".pkl")

['regLog_epochs=20_lr=1_Lasso=0.001_Ledge=0.pkl']

In [124]:
reglogcc6,regloge6,regloga6,reglogp6,reglogr6,reglogf6,regloge6v,regloga6v,reglogp6v,reglogr6v,reglogf6v,W6,B6 = train_logistica(XT=X_train, YT=Y_train, XV=X_validation, YV=Y_validation, epochs=20, LR=0.1, L1=1, L2=0)

Initialized
Iteraci√≥n en entrenamiento: 0  Costo en entranmiento: 0.94914913
Iteraci√≥n en entrenamiento: 1  Costo en entranmiento: 0.9095908
Iteraci√≥n en entrenamiento: 2  Costo en entranmiento: 0.9085826
Iteraci√≥n en entrenamiento: 3  Costo en entranmiento: 0.95977014
Iteraci√≥n en entrenamiento: 4  Costo en entranmiento: 0.9366245
Iteraci√≥n en entrenamiento: 5  Costo en entranmiento: 0.8368635
Iteraci√≥n en entrenamiento: 6  Costo en entranmiento: 0.8879509
Iteraci√≥n en entrenamiento: 7  Costo en entranmiento: 1.0211481
Iteraci√≥n en entrenamiento: 8  Costo en entranmiento: 1.0257559
Iteraci√≥n en entrenamiento: 9  Costo en entranmiento: 0.9137802
Iteraci√≥n en entrenamiento: 10  Costo en entranmiento: 0.98931724
Iteraci√≥n en entrenamiento: 11  Costo en entranmiento: 1.0061443
Iteraci√≥n en entrenamiento: 12  Costo en entranmiento: 0.91778964
Iteraci√≥n en entrenamiento: 13  Costo en entranmiento: 0.8715379
Iteraci√≥n en entrenamiento: 14  Costo en entranmiento: 0.86755466
Iteraci√≥n en entrenamiento: 15  Costo en entranmiento: 0.9365509
Iteraci√≥n en entrenamiento: 16  Costo en entranmiento: 0.86245453
Iteraci√≥n en entrenamiento: 17  Costo en entranmiento: 0.77532816
Iteraci√≥n en entrenamiento: 18  Costo en entranmiento: 0.8234379
Iteraci√≥n en entrenamiento: 19  Costo en entranmiento: 0.93722415
Accuracy de entrenamiento: 0.5625
Costo en validaci√≥n: 0.91412437
Accuracy de validaci√≥n: 0.5826087

C:\Users\Johnatan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Johnatan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Johnatan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\Johnatan\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)

In [125]:
##LLenado con valores la fila 17
sheet1.write(17, 1, reglogcc6) 
sheet1.write(17, 2, str(regloge6)) 
sheet1.write(17, 3, str(regloga6)) 
sheet1.write(17, 4, str(reglogp6))
sheet1.write(17, 5, str(reglogr6))
sheet1.write(17, 6, str(reglogf6))
sheet1.write(17, 7, str(regloge6v))
sheet1.write(17, 8, str(regloga6v)) 
sheet1.write(17, 9, str(reglogp6v)) 
sheet1.write(17, 10, str(reglogr6v))
sheet1.write(17, 11, str(reglogf6v))
sheet1.write(17, 12, "W = "+str(W6)+" B = "+str(B6))

In [126]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
joblib.dump([W6,B6], reglogcc6+".pkl")

['regLog_epochs=20_lr=0.1_Lasso=1_Ledge=0.pkl']

In [127]:
reglogcc7,regloge7,regloga7,reglogp7,reglogr7,reglogf7,regloge7v,regloga7v,reglogp7v,reglogr7v,reglogf7v,W7,B7 = train_logistica(XT=X_train, YT=Y_train, XV=X_validation, YV=Y_validation, epochs=20, LR=0.1, L1=0.01, L2=0)

Initialized
Iteraci√≥n en entrenamiento: 0  Costo en entranmiento: 0.6436519
Iteraci√≥n en entrenamiento: 1  Costo en entranmiento: 0.59196866
Iteraci√≥n en entrenamiento: 2  Costo en entranmiento: 0.6355705
Iteraci√≥n en entrenamiento: 3  Costo en entranmiento: 0.68978715
Iteraci√≥n en entrenamiento: 4  Costo en entranmiento: 0.6855177
Iteraci√≥n en entrenamiento: 5  Costo en entranmiento: 0.6652633
Iteraci√≥n en entrenamiento: 6  Costo en entranmiento: 0.6297174
Iteraci√≥n en entrenamiento: 7  Costo en entranmiento: 0.60174143
Iteraci√≥n en entrenamiento: 8  Costo en entranmiento: 0.60926884
Iteraci√≥n en entrenamiento: 9  Costo en entranmiento: 0.58205456
Iteraci√≥n en entrenamiento: 10  Costo en entranmiento: 0.50252944
Iteraci√≥n en entrenamiento: 11  Costo en entranmiento: 0.65221596
Iteraci√≥n en entrenamiento: 12  Costo en entranmiento: 0.7565091
Iteraci√≥n en entrenamiento: 13  Costo en entranmiento: 0.71741104
Iteraci√≥n en entrenamiento: 14  Costo en entranmiento: 0.60864645
Iteraci√≥n en entrenamiento: 15  Costo en entranmiento: 0.57911056
Iteraci√≥n en entrenamiento: 16  Costo en entranmiento: 0.547295
Iteraci√≥n en entrenamiento: 17  Costo en entranmiento: 0.5429007
Iteraci√≥n en entrenamiento: 18  Costo en entranmiento: 0.59007174
Iteraci√≥n en entrenamiento: 19  Costo en entranmiento: 0.6394411
Accuracy de entrenamiento: 0.71875
Costo en validaci√≥n: 0.5620222
Accuracy de validaci√≥n: 0.8086957

In [128]:
##LLenado con valores la fila 18
sheet1.write(18, 1, reglogcc7) 
sheet1.write(18, 2, str(regloge7)) 
sheet1.write(18, 3, str(regloga7)) 
sheet1.write(18, 4, str(reglogp7))
sheet1.write(18, 5, str(reglogr7))
sheet1.write(18, 6, str(reglogf7))
sheet1.write(18, 7, str(regloge7v))
sheet1.write(18, 8, str(regloga7v)) 
sheet1.write(18, 9, str(reglogp7v)) 
sheet1.write(18, 10, str(reglogr7v))
sheet1.write(18, 11, str(reglogf7v))
sheet1.write(18, 12, "W = "+str(W7)+" B = "+str(B7))

In [129]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
joblib.dump([W7,B7], reglogcc7+".pkl")

['regLog_epochs=20_lr=0.1_Lasso=0.01_Ledge=0.pkl']

In [130]:
## mejor modelo con lasso
reglogcc8,regloge8,regloga8,reglogp8,reglogr8,reglogf8,regloge8v,regloga8v,reglogp8v,reglogr8v,reglogf8v,W8,B8 = train_logistica(XT=X_train, YT=Y_train, XV=X_validation, YV=Y_validation, epochs=20, LR=0.1, L1=0.001, L2=0)

Initialized
Iteraci√≥n en entrenamiento: 0  Costo en entranmiento: 0.6367501
Iteraci√≥n en entrenamiento: 1  Costo en entranmiento: 0.5813417
Iteraci√≥n en entrenamiento: 2  Costo en entranmiento: 0.6212137
Iteraci√≥n en entrenamiento: 3  Costo en entranmiento: 0.6751527
Iteraci√≥n en entrenamiento: 4  Costo en entranmiento: 0.67318636
Iteraci√≥n en entrenamiento: 5  Costo en entranmiento: 0.6522642
Iteraci√≥n en entrenamiento: 6  Costo en entranmiento: 0.61447996
Iteraci√≥n en entrenamiento: 7  Costo en entranmiento: 0.58512896
Iteraci√≥n en entrenamiento: 8  Costo en entranmiento: 0.59107995
Iteraci√≥n en entrenamiento: 9  Costo en entranmiento: 0.558866
Iteraci√≥n en entrenamiento: 10  Costo en entranmiento: 0.47200832
Iteraci√≥n en entrenamiento: 11  Costo en entranmiento: 0.6388398
Iteraci√≥n en entrenamiento: 12  Costo en entranmiento: 0.7501496
Iteraci√≥n en entrenamiento: 13  Costo en entranmiento: 0.7070933
Iteraci√≥n en entrenamiento: 14  Costo en entranmiento: 0.592199
Iteraci√≥n en entrenamiento: 15  Costo en entranmiento: 0.5532123
Iteraci√≥n en entrenamiento: 16  Costo en entranmiento: 0.52461743
Iteraci√≥n en entrenamiento: 17  Costo en entranmiento: 0.5245703
Iteraci√≥n en entrenamiento: 18  Costo en entranmiento: 0.5781091
Iteraci√≥n en entrenamiento: 19  Costo en entranmiento: 0.62136286
Accuracy de entrenamiento: 0.6875
Costo en validaci√≥n: 0.5341575
Accuracy de validaci√≥n: 0.773913

In [131]:
##LLenado con valores la fila 19
sheet1.write(19, 1, reglogcc8) 
sheet1.write(19, 2, str(regloge8)) 
sheet1.write(19, 3, str(regloga8)) 
sheet1.write(19, 4, str(reglogp8))
sheet1.write(19, 5, str(reglogr8))
sheet1.write(19, 6, str(reglogf8))
sheet1.write(19, 7, str(regloge8v))
sheet1.write(19, 8, str(regloga8v)) 
sheet1.write(19, 9, str(reglogp8v)) 
sheet1.write(19, 10, str(reglogr8v))
sheet1.write(19, 11, str(reglogf8v))
sheet1.write(19, 12, "W = "+str(W8)+" B = "+str(B8))

In [132]:
## escribriendo, guardando o exportando los modelos al disco duro 
## guardar o exportar al disco duro el modelo entrenado
## la W y la B se guardan como lista pues estan separadas
joblib.dump([W8,B8], reglogcc8+".pkl")

['regLog_epochs=20_lr=0.1_Lasso=0.001_Ledge=0.pkl']

## Naive Bayes

In [133]:
## no lo tengo
n_b = "modelo"

In [134]:
## escribiendo el archivo de excel al disco duro
## escribiendo el archivo de excel al disco duro
## escribiendo el archivo de excel al disco duro
## escribiendo el archivo de excel al disco duro
## escribiendo el archivo de excel al disco duro
## escribiendo el archivo de excel al disco duro
## escribiendo el archivo de excel al disco duro
wb.save('Resumen.xls')

# K-fold

### ¬øC√≥mo se pudo haber aplicado en este proyecto?

### Es una t√©cnica que garantiza que cada observacion del datase original tenga la misma oportunidad de aparecer en data set de etrnteamiento y de prueba. En este proyecto se hubiera implementado utilizando from sklearn.model_selection import KFold, generando 4 dobleces uno para cada modelo a implementar

# Predicciones

In [136]:
## lista pra almacenar los modelos
estimadores = [d_t_modelo5,svm_modelo2,[W5,B5],n_b]

# Predicci√≥n por mayor√≠a

# Predicci√≥nes en data test con decision tree

In [137]:
Y_Test_predic_dt = estimadores[0].predict(X_test)
Y_Test_predic_dt.shape

(143,)

# Predicci√≥nes en data test con SVM

In [138]:
Y_Test_predic_svm = estimadores[1].predict(X_test)
Y_Test_predic_svm.shape

(143,)

# Predicci√≥nes en data test con regresi√≥n logistica

In [139]:
## con doble uso de corchete para sacar de la lista otra lista
(np.matmul(X_test,estimadores[2][0])+estimadores[2][1])*-1

array([[-0.57924896],
       [-0.45943018],
       [ 2.02824183],
       [ 0.27119372],
       [ 0.9544851 ],
       [-1.61866468],
       [ 1.5408012 ],
       [ 1.28344217],
       [-1.42945384],
       [-0.76409192],
       [-0.71678921],
       [ 1.53156339],
       [-1.5555944 ],
       [-1.30747318],
       [-1.72903766],
       [-1.37707322],
       [-0.97343819],
       [ 0.42886941],
       [-0.36266287],
       [ 0.27119372],
       [ 0.0516618 ],
       [ 1.40958272],
       [ 1.39381516],
       [ 1.20304232],
       [ 0.15081132],
       [ 0.95011723],
       [ 1.28344217],
       [-0.74616246],
       [-1.24656479],
       [ 1.28344217],
       [ 1.35439623],
       [-1.08164929],
       [-1.09533691],
       [ 1.60511534],
       [-1.19926208],
       [ 0.55500997],
       [ 1.64609627],
       [-0.80923274],
       [-0.77985949],
       [-1.69958247],
       [ 1.44111786],
       [-0.37198263],
       [ 1.46320722],
       [ 1.37804759],
       [ 1.29908371],
       [ 1.05325041],
       [-1.37707322],
       [ 0.52347483],
       [ 0.03536041],
       [-0.70102164],
       [ 1.23613946],
       [ 0.47617212],
       [-1.36638356],
       [ 1.49141854],
       [-0.3490572 ],
       [-1.3979187 ],
       [-1.72903766],
       [-1.5555944 ],
       [ 1.43674999],
       [-0.52125659],
       [ 0.54432032],
       [-1.02581882],
       [ 1.58810391],
       [ 1.53572328],
       [ 1.31060944],
       [ 1.59879356],
       [ 1.04256076],
       [-0.89967826],
       [-0.13754903],
       [ 2.10373999],
       [ 1.2676746 ],
       [ 1.3686018 ],
       [ 0.39733427],
       [-0.79346517],
       [-0.52541649],
       [-0.5540356 ],
       [ 1.60179153],
       [-0.94698097],
       [ 0.83250444],
       [ 1.53572328],
       [ 1.31497731],
       [-0.68525407],
       [-0.42789504],
       [-1.20870787],
       [ 1.42535029],
       [ 1.23613946],
       [ 1.19515854],
       [ 0.53155072],
       [ 2.09005236],
       [ 1.78800439],
       [-0.3376575 ],
       [-0.56348139],
       [ 1.46476922],
       [ 1.67925948],
       [ 0.35003156],
       [-0.65371893],
       [-0.76617187],
       [-1.61866468],
       [ 1.53996512],
       [-0.63795136],
       [ 0.00798517],
       [ 1.23613946],
       [ 2.58890857],
       [ 1.45688543],
       [-0.22636649],
       [-0.58432687],
       [ 0.84390414],
       [ 1.2109261 ],
       [ 1.58302599],
       [-1.05227604],
       [-0.76409192],
       [ 1.55656877],
       [ 1.472653  ],
       [ 1.33074488],
       [-1.04366633],
       [-1.38123311],
       [ 1.49349849],
       [-0.61710588],
       [ 1.1594635 ],
       [ 0.42886941],
       [ 1.2676746 ],
       [ 1.40521486],
       [ 0.86403957],
       [ 1.94098638],
       [-0.85237555],
       [-1.34969797],
       [ 1.33074488],
       [-1.16772694],
       [ 1.14785583],
       [ 1.23613946],
       [ 1.25190703],
       [ 1.27191644],
       [-1.40860836],
       [ 1.19337918],
       [ 1.44111786],
       [-1.02581882],
       [ 2.15065849],
       [-1.46098898],
       [ 1.86930639],
       [ 0.40033224],
       [ 1.63332667],
       [-1.12042424],
       [-0.92176762]])

In [140]:
Y_Test_predic_reglog = ((1/(1+np.exp((np.matmul(X_test,estimadores[2][0])+estimadores[2][1])*-1)))>=0.5)*1
Y_Test_predic_reglog.shape

(143, 1)

# Predicci√≥nes en data test con Naive Bayes

# Tabla Resumen de Ensamble Learning

In [141]:
Tabla_moda = pd.DataFrame({'Y_Test_predic_dt':Y_Test_predic_dt,'Y_Test_predic_svm': Y_Test_predic_svm,
                           'Y_Test_predic_reglog': Y_Test_predic_reglog.reshape(143)})

In [142]:
Tabla_moda

     Y_Test_predic_dt  Y_Test_predic_svm  Y_Test_predic_reglog
0                 1.0                1.0                     1
1                 0.0                1.0                     1
2                 0.0                0.0                     0
3                 0.0                0.0                     0
4                 1.0                0.0                     0
5                 1.0                1.0                     1
6                 0.0                0.0                     0
7                 0.0                0.0                     0
8                 1.0                1.0                     1
9                 1.0                1.0                     1
10                1.0                1.0                     1
11                0.0                0.0                     0
12                1.0                1.0                     1
13                1.0                1.0                     1
14                1.0                1.0                     1
15                1.0                1.0                     1
16                1.0                1.0                     1
17                0.0                0.0                     0
18                1.0                1.0                     1
19                0.0                0.0                     0
20                0.0                1.0                     0
21                0.0                0.0                     0
22                0.0                0.0                     0
23                0.0                0.0                     0
24                0.0                0.0                     0
25                0.0                0.0                     0
26                0.0                0.0                     0
27                1.0                1.0                     1
28                1.0                1.0                     1
29                0.0                0.0                     0
..                ...                ...                   ...
113               0.0                0.0                     0
114               1.0                1.0                     1
115               1.0                1.0                     1
116               0.0                0.0                     0
117               0.0                1.0                     1
118               0.0                0.0                     0
119               0.0                0.0                     0
120               0.0                0.0                     0
121               0.0                0.0                     0
122               0.0                0.0                     0
123               1.0                0.0                     0
124               1.0                1.0                     1
125               1.0                1.0                     1
126               0.0                0.0                     0
127               1.0                1.0                     1
128               0.0                0.0                     0
129               0.0                0.0                     0
130               0.0                0.0                     0
131               0.0                0.0                     0
132               1.0                1.0                     1
133               1.0                0.0                     0
134               0.0                0.0                     0
135               1.0                1.0                     1
136               0.0                0.0                     0
137               1.0                1.0                     1
138               0.0                0.0                     0
139               1.0                0.0                     0
140               0.0                0.0                     0
141               1.0                1.0                     1
142               1.0                1.0                     1

[143 rows x 3 columns]

In [143]:
Calculo_moda = Tabla_moda.mode(axis=1)

In [144]:
Tabla_moda['Moda'] = Calculo_moda

In [145]:
Tabla_moda

     Y_Test_predic_dt  Y_Test_predic_svm  Y_Test_predic_reglog  Moda
0                 1.0                1.0                     1   1.0
1                 0.0                1.0                     1   1.0
2                 0.0                0.0                     0   0.0
3                 0.0                0.0                     0   0.0
4                 1.0                0.0                     0   0.0
5                 1.0                1.0                     1   1.0
6                 0.0                0.0                     0   0.0
7                 0.0                0.0                     0   0.0
8                 1.0                1.0                     1   1.0
9                 1.0                1.0                     1   1.0
10                1.0                1.0                     1   1.0
11                0.0                0.0                     0   0.0
12                1.0                1.0                     1   1.0
13                1.0                1.0                     1   1.0
14                1.0                1.0                     1   1.0
15                1.0                1.0                     1   1.0
16                1.0                1.0                     1   1.0
17                0.0                0.0                     0   0.0
18                1.0                1.0                     1   1.0
19                0.0                0.0                     0   0.0
20                0.0                1.0                     0   0.0
21                0.0                0.0                     0   0.0
22                0.0                0.0                     0   0.0
23                0.0                0.0                     0   0.0
24                0.0                0.0                     0   0.0
25                0.0                0.0                     0   0.0
26                0.0                0.0                     0   0.0
27                1.0                1.0                     1   1.0
28                1.0                1.0                     1   1.0
29                0.0                0.0                     0   0.0
..                ...                ...                   ...   ...
113               0.0                0.0                     0   0.0
114               1.0                1.0                     1   1.0
115               1.0                1.0                     1   1.0
116               0.0                0.0                     0   0.0
117               0.0                1.0                     1   1.0
118               0.0                0.0                     0   0.0
119               0.0                0.0                     0   0.0
120               0.0                0.0                     0   0.0
121               0.0                0.0                     0   0.0
122               0.0                0.0                     0   0.0
123               1.0                0.0                     0   0.0
124               1.0                1.0                     1   1.0
125               1.0                1.0                     1   1.0
126               0.0                0.0                     0   0.0
127               1.0                1.0                     1   1.0
128               0.0                0.0                     0   0.0
129               0.0                0.0                     0   0.0
130               0.0                0.0                     0   0.0
131               0.0                0.0                     0   0.0
132               1.0                1.0                     1   1.0
133               1.0                0.0                     0   0.0
134               0.0                0.0                     0   0.0
135               1.0                1.0                     1   1.0
136               0.0                0.0                     0   0.0
137               1.0                1.0                     1   1.0
138               0.0                0.0                     0   0.0
139               1.0                0.0                     0   0.0
140               0.0                0.0                     0   0.0
141               1.0                1.0                     1   1.0
142               1.0                1.0                     1   1.0

[143 rows x 4 columns]

In [146]:
## copiando la columna moda
mooda = Tabla_moda['Moda'].copy()

In [147]:
## convirtiendo la columan moda a tipo usado en numpy
y_emsamble = mooda.values

# Tabla Resumen de M√©tricas

In [148]:
## M√©tricas de Arbol 
Error_Test_dt = brier_score_loss(Y_test, Y_Test_predic_dt)
Accuracy_Test_dt = accuracy_score(Y_test, Y_Test_predic_dt, normalize = True)
Precision_Test_dt = precision_score(Y_test, Y_Test_predic_dt)
Recall_Test_dt = recall_score(Y_test, Y_Test_predic_dt)
F1_Test_dt = f1_score(Y_test, Y_Test_predic_dt)

In [149]:
print(Accuracy_Test_dt)

0.8321678321678322

In [150]:
## M√©tricas SVM
Error_Test_svm = brier_score_loss(Y_test, Y_Test_predic_svm)
Accuracy_Test_svm = accuracy_score(Y_test, Y_Test_predic_svm, normalize = True)
Precision_Test_svm = precision_score(Y_test, Y_Test_predic_svm)
Recall_Test_svm = recall_score(Y_test, Y_Test_predic_svm)
F1_Test_svm = f1_score(Y_test, Y_Test_predic_svm)

In [151]:
print(Accuracy_Test_svm)

0.8041958041958042

In [152]:
## Metricas regresion logistica 
Error_Test_reglog = brier_score_loss(Y_test, Y_Test_predic_reglog)
Accuracy_Test_reglog = accuracy_score(Y_test, Y_Test_predic_reglog, normalize = True)
Precision_Test_reglog = precision_score(Y_test, Y_Test_predic_reglog)
Recall_Test_reglog = recall_score(Y_test, Y_Test_predic_reglog)
F1_Test_reglog = f1_score(Y_test, Y_Test_predic_reglog)

In [153]:
print(Accuracy_Test_reglog)

0.8181818181818182

In [154]:
## Metricas naive bayes

In [155]:
## Metricas de emsamble
Error_emsamble = brier_score_loss(Y_test, y_emsamble)
Accuracy_emsamble = accuracy_score(Y_test, y_emsamble, normalize = True)
Precision_emsamble = precision_score(Y_test, y_emsamble)
Recall_emsamble = recall_score(Y_test, y_emsamble)
F1_emsamble = f1_score(Y_test, y_emsamble)

In [156]:
print(Accuracy_emsamble)

0.8181818181818182

In [157]:
lista1 = ["Emsamble Learning","Decision Tree","SVM","Regresi√≥n Logistica"]

In [158]:
lista2 = [Error_emsamble,Error_Test_dt,Error_Test_svm,Error_Test_reglog]

In [159]:
lista3 = [Accuracy_emsamble,Accuracy_Test_dt,Accuracy_Test_svm,Accuracy_Test_reglog]

In [160]:
lista4 = [Precision_emsamble,Precision_Test_dt,Precision_Test_svm,Precision_Test_reglog]

In [161]:
lista5 = [Recall_emsamble,Recall_Test_dt,Recall_Test_svm,Recall_Test_reglog]

In [162]:
lista6 = [F1_emsamble,F1_Test_dt,F1_Test_svm,F1_Test_reglog]

In [163]:
Metricas = pd.DataFrame({'Nombre del Modelo':lista1,'Error':lista2,'Accuracy':lista3,
                         'Precision':lista4,'Recall':lista5,'f1Score':lista6,})

In [164]:
Metricas

     Nombre del Modelo     Error  Accuracy  Precision    Recall   f1Score
0    Emsamble Learning  0.181818  0.818182   0.850000  0.750000  0.796875
1        Decision Tree  0.167832  0.832168   0.866667  0.764706  0.812500
2                  SVM  0.195804  0.804196   0.833333  0.735294  0.781250
3  Regresi√≥n Logistica  0.181818  0.818182   0.850000  0.750000  0.796875

# Conclusiones

### A partir de la votaci√≥n de los modelos, se logra que el valor de las metricas se eleve.

### Accuracy: el emsable learning hace un 81.81% de predicciones correctas 

### Precision: de todo lo que el emsable learning predijo que era 1 el 85 si lo eran 

### Recall: de las observaciones que eran 1 el esamble learning indico que 75% s√≠ lo eran  

### f1Score: el f1score del emsamble es relativamente alto en 79.68%, podriamos usar esta metrica si tanto la precision como el recall fueran importantes para la toma de decisiones

### En este proyecto al aplicar regularizaci√≥n L1(Lasso) no se observo que la variaci√≥n del hiperparametro diera como resultados valores de los estimadors cercanos a cero lo cual permitiria saber si se podian eliminar features. 

### Al realizar los calculos se habia obentido una precision del 85% sin embargo al abrir de nuevo el archivo y correr de nuevo los modelos, √©sta precision fue cambiando, ya que al hacer el bootstrapping los data set (train, validation, test) variaban, por lo que se pregunto al profesor si era necesarrio dejar fija la muestra, a lo cual respond√≠o que no era necesario

### todo lo anterior tambien impacta en que el modelo que habia salido como mejor la primera vez, podia ya no ser el mejor al abrir el archivo en otro momento  

### Sin embargo invetigando se termino que si se puede dejar una muestra fija en el mustreo aplicando random_state=seem

### Afinar los modelos que se calculan a partir de los comandos de sklearn es un poco ambiguo, me parece mejor afinar los modelos a partir de generar un codigo con tensor flow ya que se tiene mas control sobre cada parametro y se conoce mas de como trabaja el codigo

### Area de pruebas

In [ ]:
def predcit_voting(estimadores,features):
    
    prediciones_dt = [] ## en esta lista se guardan los resultaso del modelo
    prediciones_svm = [] ## en esta lista se guardan los resultaso del modelo
    prediciones_relog = [] ## en esta lista se guardan los resultaso del modelo
    
    ##desicion tree
    estimadores[0].predict(features)
    
    ##svm
    
    ##reglogistica
    
    ##bayes

In [271]:
## Guardado de modelos al disco 
## guardando los modelos generados con sklearn
#import pickle 
# nombre de guardado del modelo = pickle.dumps(nombre del modelo escogido de sklearn)
# nombre de carga del modelo = pickle.load(nombre de guardado del modelo)
# nombre de carga del modelo.predict() # aca ya estoy usando el modelo

In [ ]:
## guardando los modelos generados con sklearn
# from sklearn.externals import jolib
# guardar o exportar al disco duro el modelo entrenado
# joblib.dump(nombre del modelo escogido de sklearn, "filename.pkl")

# caganado el modelo en otro notebook y ulizarlo para predecir
# nombre de carga del modelo = joblib.load("filename.pkl")
# nombre de carga del modelo.predict() # aca ya estoy usando el modelo

In [143]:
## prueba de carga de un modelo guardado
prueba = joblib.load("regLog_epochs=20_lr=0.1_Lasso=0_Ledge=0.pkl")

In [147]:
prueba[1]

-0.8391876

In [ ]:
## codigo backup no correrlo

In [99]:
Leq quito la w a with para que no trabaje 
ith tf.Session(graph = grafologistica) as session:
    # incializando variables
    tf.global_variables_initializer().run()
    print('Initialized')
    
    for epoch in range(epochs):
        for i in range(batches):
            offset = i * epoch 
            x = X_train[offset: offset + batch_size] ## slicing de filas
            y = Y_train[offset: offset + batch_size] ## slicing de filas
            _, final_W, final_B, train_accuracy = session.run([optimizacion, W, B, accuracy], feed_dict={X:x, Y:y, ph_lr:0.001, l1_g:0.0, l2_g:0.0})
            cost_s = session.run(cost_g, feed_dict={X:x, Y:y, ph_lr:0.001, l1_g:0.0, l2_g:0.0})
                                                          
        if (epoch % 1 == 0):
            print("Iteraci√≥n en entrenamiento: ", epoch, "Costo en entranmiento: ", cost_s)
    print("Accuracy de entrenamiento: ", train_accuracy)
    
    ## usando el grafo con otros datos 
    _yhatvalida, errorvalida, accuracyvalida = session.run([yhat_g, cost_g, accuracy], feed_dict={X:X_validation, Y:Y_validation, l1_g:0.0, l2_g:0.0})
    #print("pronostico en validaci√≥n: ", _yhatvalida)
    print("Costo en validaci√≥n: ", errorvalida)
    print("Accuracy de validaci√≥n: ", accuracyvalida)

Initialized
Iteraci√≥n en entrenamiento:  0 Costo en entranmiento:  0.6812029
Iteraci√≥n en entrenamiento:  1 Costo en entranmiento:  0.6869062
Iteraci√≥n en entrenamiento:  2 Costo en entranmiento:  0.5898305
Iteraci√≥n en entrenamiento:  3 Costo en entranmiento:  0.6424974
Iteraci√≥n en entrenamiento:  4 Costo en entranmiento:  0.651664
Iteraci√≥n en entrenamiento:  5 Costo en entranmiento:  0.61774087
Iteraci√≥n en entrenamiento:  6 Costo en entranmiento:  0.60623837
Iteraci√≥n en entrenamiento:  7 Costo en entranmiento:  0.5283544
Iteraci√≥n en entrenamiento:  8 Costo en entranmiento:  0.6958332
Iteraci√≥n en entrenamiento:  9 Costo en entranmiento:  0.6662206
Iteraci√≥n en entrenamiento:  10 Costo en entranmiento:  0.70774174
Iteraci√≥n en entrenamiento:  11 Costo en entranmiento:  0.6834185
Iteraci√≥n en entrenamiento:  12 Costo en entranmiento:  0.67519534
Iteraci√≥n en entrenamiento:  13 Costo en entranmiento:  0.6071218
Iteraci√≥n en entrenamiento:  14 Costo en entranmiento:  0.6630869
Iteraci√≥n en entrenamiento:  15 Costo en entranmiento:  0.70226604
Iteraci√≥n en entrenamiento:  16 Costo en entranmiento:  0.67820257
Iteraci√≥n en entrenamiento:  17 Costo en entranmiento:  0.66378903
Iteraci√≥n en entrenamiento:  18 Costo en entranmiento:  0.707161
Iteraci√≥n en entrenamiento:  19 Costo en entranmiento:  0.69580525
Accuracy de entrenamiento:  0.46875
Costo en validaci√≥n:  0.6690158
Accuracy de validaci√≥n:  0.6347826

In [100]:
final_W

array([[-0.00691339],
       [-0.0149137 ],
       [ 0.00802235],
       [ 0.03002457],
       [ 0.03443415]], dtype=float32)

In [101]:
final_B

0.0048369253

In [102]:
cost_s

0.69580525

In [247]:
print("hola "+str(50))

hola 50

In [247]:
print("hola "+str(50))

hola 50

### Bibliografia 

https://www.kaggle.com/reneang/logistic-regression-titanic-survival

https://www.analyticslane.com/2019/03/25/como-eliminar-columnas-y-filas-en-un-dataframe-pandas/

https://www.interviewqs.com/ddi_code_snippets/add_new_col_df_default_value

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html

https://scikit-learn.org/stable/modules/tree.html

https://scikit-learn.org/stable/modules/svm.html

https://www.geeksforgeeks.org/ml-logistic-regression-using-tensorflow/

https://www.kaggle.com/autuanliuyc/logistic-regression-with-tensorflow

https://www.geeksforgeeks.org/ml-logistic-regression-using-tensorflow/

https://www.dotnetperls.com/cast-tensorflow

https://www.youtube.com/watch?v=0OVldHsRxTs&feature=youtu.be

https://github.com/markjay4k/Tensorflow-Basics-Series/blob/master/part%202%20-%20Logistic%20Regression.ipynb

http://benalexkeen.com/decision-tree-classifier-in-python-using-scikit-learn/

https://stackoverflow.com/questions/43095076/scikit-learn-train-test-split-can-i-ensure-same-splits-on-different-datasets

https://pandas.pydata.org/pandas-docs/version/0.17/generated/pandas.DataFrame.mode.html